import {
  Activity,
  BarChart2,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CirclePlay,
  CirclePlus,
  Clock3,
  Cloud,
  Droplet,
  Ellipsis,
  Eye,
  Grid2x2,
  Heart,
  Layers,
  Link,
  List,
  Map,
  MapPin,
  Maximize2,
  MessageCircle,
  Moon,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  Target,
  User,
  Watch,
  Wind,
  X,
  Zap,
} from "lucide-react-native";
import React from "react";

const ICONS = {
  activity: Activity,
  "bar-chart-2": BarChart2,
  calendar: Calendar,
  check: Check,
  "check-circle": CircleCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  clock: Clock3,
  cloud: Cloud,
  droplet: Droplet,
  "edit-3": Pencil,
  eye: Eye,
  grid: Grid2x2,
  heart: Heart,
  layers: Layers,
  link: Link,
  list: List,
  map: Map,
  "map-pin": MapPin,
  "maximize-2": Maximize2,
  "message-circle": MessageCircle,
  moon: Moon,
  "more-horizontal": Ellipsis,
  play: Play,
  "play-circle": CirclePlay,
  plus: Plus,
  "plus-circle": CirclePlus,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "skip-forward": SkipForward,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  target: Target,
  user: User,
  watch: Watch,
  wind: Wind,
  x: X,
  zap: Zap,
};

export default function LucideFeather({
  name,
  size = 16,
  color = "currentColor",
  strokeWidth = 2.25,
  style,
}) {
  const Icon = ICONS[String(name || "").toLowerCase()] || Activity;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}
