const easy = "easy";
const walkRun = "walk_run";

function walkRunBlock(repeatCount, runSec, walkSec) {
  return {
    type: "REPEAT",
    repeatCount,
    work: { valueSec: runSec, intensity: "EASY", intensityKey: easy },
    recover: { valueSec: walkSec, intensity: "WALK", intensityKey: "recovery" },
  };
}

const template = {
  id: "return_6w_3run",
  metadata: {
    distance: "RETURN",
    level: "beginner",
    weeks: 6,
    runsPerWeek: 3,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      focus: "Restart gently with short run-walk sessions",
      coachNote: "This week is about proving the routine is safe and repeatable, not testing fitness.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: walkRun,
          fixedDistanceKm: 1.5,
          structure: "6 x 90 sec easy run / 60 sec walk",
          purpose: "Reintroduce impact in small doses while keeping confidence high.",
          executionTip: "Run the easy parts softly and walk before you feel you need to.",
          workout: { kind: "EASY", blocks: [walkRunBlock(6, 90, 60)] },
        },
        {
          role: "support",
          type: "EASY",
          target: walkRun,
          fixedDistanceKm: 1.5,
          structure: "8 x 1 min easy run / 1 min walk",
          purpose: "Build a second low-stress touchpoint without chasing volume.",
          executionTip: "Keep the run sections very relaxed and stop early if anything feels sharp.",
          workout: { kind: "EASY", blocks: [walkRunBlock(8, 60, 60)] },
        },
        {
          role: "long_run",
          type: "LONG",
          target: walkRun,
          fixedDistanceKm: 2,
          structure: "Relaxed walk-run endurance",
          purpose: "Extend time on feet gently while keeping the effort comfortable.",
          executionTip: "Use short walk breaks early so the whole session stays calm.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      focus: "Repeat the rhythm with a small time increase",
      coachNote: "Progression stays modest so tissues adapt before the plan asks for longer running.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: walkRun,
          fixedDistanceKm: 1.8,
          structure: "6 x 2 min easy run / 60 sec walk",
          purpose: "Add a little continuous running while preserving recovery breaks.",
          executionTip: "Keep the same effort as Week 1 even though the run portions are longer.",
          workout: { kind: "EASY", blocks: [walkRunBlock(6, 120, 60)] },
        },
        {
          role: "support",
          type: "EASY",
          target: walkRun,
          fixedDistanceKm: 1.8,
          structure: "8 x 75 sec easy run / 45 sec walk",
          purpose: "Improve consistency with a second gentle run-walk day.",
          executionTip: "If the legs feel heavy, keep the run sections slower rather than shortening the walk.",
          workout: { kind: "EASY", blocks: [walkRunBlock(8, 75, 45)] },
        },
        {
          role: "long_run",
          type: "LONG",
          target: walkRun,
          fixedDistanceKm: 2.3,
          structure: "Easy walk-run longer outing",
          purpose: "Build confidence over a slightly longer relaxed session.",
          executionTip: "Finish with the same easy form you started with.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      focus: "Grow easy running without adding intensity",
      coachNote: "The build remains aerobic and controlled, with no faster workout pressure.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: walkRun,
          fixedDistanceKm: 2,
          structure: "5 x 3 min easy run / 90 sec walk",
          purpose: "Increase easy running time while keeping impact manageable.",
          executionTip: "Stay patient. The correct pace should feel almost too easy.",
          workout: { kind: "EASY", blocks: [walkRunBlock(5, 180, 90)] },
        },
        {
          role: "support",
          type: "EASY",
          target: walkRun,
          fixedDistanceKm: 2.2,
          structure: "10 x 90 sec easy run / 45 sec walk",
          purpose: "Add steady practice with frequent recovery breaks.",
          executionTip: "Use the walk breaks to reset posture and breathing.",
          workout: { kind: "EASY", blocks: [walkRunBlock(10, 90, 45)] },
        },
        {
          role: "long_run",
          type: "LONG",
          target: walkRun,
          fixedDistanceKm: 2.8,
          structure: "Relaxed walk-run endurance",
          purpose: "Extend the long outing conservatively for durability.",
          executionTip: "Keep this easier than your weekday runs and avoid pushing the last few minutes.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      focus: "Back off slightly and absorb the restart",
      coachNote: "A lighter week reduces injury risk and checks that the routine still feels sustainable.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: walkRun,
          fixedDistanceKm: 1.8,
          structure: "6 x 2 min easy run / 75 sec walk",
          purpose: "Maintain the habit while trimming the load.",
          executionTip: "Keep every run section smooth and stop if niggles build.",
          workout: { kind: "EASY", blocks: [walkRunBlock(6, 120, 75)] },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2,
          structure: "Very easy continuous jog or walk-run",
          purpose: "Practice relaxed movement without forcing continuous running.",
          executionTip: "Choose walk-run if that keeps the session pain-free and enjoyable.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: walkRun,
          fixedDistanceKm: 2.5,
          structure: "Reduced relaxed longer outing",
          purpose: "Keep time on feet without carrying fatigue into the next build.",
          executionTip: "Finish fresh. This is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      focus: "Move toward more continuous easy running",
      coachNote: "The plan nudges up running continuity while staying below workout intensity.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2.4,
          structure: "Easy continuous jog with walk breaks if needed",
          purpose: "Build confidence in relaxed continuous running.",
          executionTip: "Take short walk breaks early if they help keep the effort easy.",
        },
        {
          role: "support",
          type: "EASY",
          target: walkRun,
          fixedDistanceKm: 2.6,
          structure: "4 x 5 min easy run / 90 sec walk",
          purpose: "Extend easy run blocks while retaining planned recovery.",
          executionTip: "Do not turn the longer run blocks into a test.",
          workout: { kind: "EASY", blocks: [walkRunBlock(4, 300, 90)] },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 3.2,
          structure: "Easy longer run-walk",
          purpose: "Build low-risk endurance and confidence over the longest outing so far.",
          executionTip: "Keep the pace conversational and protect form over distance.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      focus: "Finish with a confident easy-running week",
      coachNote: "The final week confirms consistency and leaves space to continue building after the plan.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2.8,
          structure: "Easy continuous jog with walk breaks optional",
          purpose: "Practice an easy, sustainable rhythm without intensity.",
          executionTip: "Stay relaxed enough that you could repeat this session later in the week.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 3,
          structure: "Easy confidence run",
          purpose: "Reinforce the three-run habit with a calm midweek run.",
          executionTip: "Keep it enjoyable and avoid comparing pace to old fitness.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 3.8,
          structure: "Relaxed longest outing",
          purpose: "End the return block with a controlled, confidence-building endurance run.",
          executionTip: "Use walk breaks if needed so the final ten minutes stay comfortable.",
        },
      ],
    },
  ],
};

export default template;
