const easy = "easy";
const steady = "steady";

function steadyBlock(minutes, repeatCount = 1, recoverySec = 120) {
  return {
    type: "REPEAT",
    repeatCount,
    work: { valueSec: minutes * 60, intensity: "STEADY", intensityKey: steady },
    recover: { valueSec: recoverySec, intensity: "EASY", intensityKey: easy },
  };
}

const template = {
  id: "general_8w_3run",
  metadata: {
    distance: "GENERAL",
    level: "beginner",
    weeks: 8,
    runsPerWeek: 3,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      focus: "Build a repeatable fitness routine",
      coachNote: "Start with relaxed running so consistency comes before pace or distance.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2.5,
          structure: "Easy aerobic run",
          purpose: "Build aerobic health with a low-stress first session.",
          executionTip: "Keep the effort relaxed and finish feeling like you could do more.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2.5,
          structure: "Short easy support run",
          purpose: "Add frequency without making the week feel demanding.",
          executionTip: "Run by feel and keep breathing controlled throughout.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 3,
          structure: "Easy longer run",
          purpose: "Build comfortable endurance for general fitness.",
          executionTip: "Keep the first half especially easy so the run stays enjoyable.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      focus: "Add relaxed strides for variety",
      coachNote: "Short strides add smoothness and enjoyment without turning the week race-specific.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2.8,
          structure: "Easy aerobic run",
          purpose: "Keep the routine moving with relaxed aerobic work.",
          executionTip: "Stay comfortable and ignore pace if the legs feel flat.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2.8,
          structure: "Easy run with 4 relaxed strides",
          purpose: "Add a little coordination and leg speed without workout fatigue.",
          executionTip: "Strides should feel smooth and playful, never forced.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 3.5,
          structure: "Easy longer run",
          purpose: "Build aerobic durability through a slightly longer relaxed outing.",
          executionTip: "Keep the pace easy enough that the final minutes feel controlled.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      focus: "Introduce light steady running",
      coachNote: "A small steady block adds fitness variety while staying well below hard workout intensity.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 3,
          structure: "Easy aerobic run",
          purpose: "Support consistency before the light steady day.",
          executionTip: "Keep this easier than the steady session.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          fixedDistanceKm: 3,
          structure: "2 x 5 min light steady with easy recovery",
          purpose: "Improve aerobic fitness with controlled rhythm, not race-specific effort.",
          executionTip: "Steady means comfortably controlled. Back off if it feels hard.",
          workout: { kind: "EASY", blocks: [steadyBlock(5, 2, 120)] },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 4,
          structure: "Easy longer run",
          purpose: "Extend endurance in a manageable way.",
          executionTip: "Keep it conversational and let the distance be the stimulus.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      focus: "Refresh while keeping the habit",
      coachNote: "This week trims the load so the next block can build without accumulating fatigue.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2.5,
          structure: "Relaxed deload easy run",
          purpose: "Maintain rhythm while lowering training stress.",
          executionTip: "Keep the run gentle from start to finish.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 2.5,
          structure: "Short easy support run",
          purpose: "Keep frequency without adding intensity.",
          executionTip: "Short, calm, and comfortable is the target.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 3.2,
          structure: "Reduced easy longer run",
          purpose: "Protect recovery while keeping an endurance touchpoint.",
          executionTip: "Finish fresh and avoid adding extra distance.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      focus: "Build fitness with steady control and strides",
      coachNote: "The plan adds variety through relaxed strides while keeping the main work aerobic.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 3.2,
          structure: "Easy aerobic run",
          purpose: "Rebuild gently after the deload week.",
          executionTip: "Let the pace come naturally and keep the effort easy.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          fixedDistanceKm: 3.2,
          structure: "Easy run with 5 relaxed strides",
          purpose: "Improve running economy while keeping the session light.",
          executionTip: "Float through the strides and recover fully between them.",
          meta: { includeStrides: true, strides: 5 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 4.5,
          structure: "Easy longer run",
          purpose: "Build comfortable aerobic capacity.",
          executionTip: "Keep the final third relaxed, not fast.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      focus: "Extend the light steady stimulus",
      coachNote: "A slightly longer steady block supports general fitness without becoming race preparation.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 3.5,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume steady around the steady-support day.",
          executionTip: "Stay conversational and finish comfortably.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          fixedDistanceKm: 3.5,
          structure: "2 x 6 min light steady with easy recovery",
          purpose: "Build controlled aerobic strength for everyday fitness.",
          executionTip: "Use steady effort only if it feels smooth; otherwise keep it easy.",
          workout: { kind: "EASY", blocks: [steadyBlock(6, 2, 120)] },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 5,
          structure: "Easy longer run",
          purpose: "Extend endurance while keeping the week approachable.",
          executionTip: "Run the first kilometre especially easy and settle gradually.",
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "BUILD",
      focus: "Peak the routine without race-specific work",
      coachNote: "This is the fullest week, but it stays aerobic and controlled.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 3.8,
          structure: "Easy aerobic run",
          purpose: "Support the peak week with relaxed aerobic volume.",
          executionTip: "Do not push pace just because fitness is improving.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          fixedDistanceKm: 3.8,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Keep variety and smooth mechanics without hard training.",
          executionTip: "Stay tall and relaxed during each stride.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 5.5,
          structure: "Easy longest run",
          purpose: "Build confidence and aerobic durability through the longest relaxed outing.",
          executionTip: "Keep the entire run sustainable and avoid finishing hard.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "DELOAD",
      focus: "Finish fresh and ready to continue",
      coachNote: "The final week backs off slightly so the plan ends with confidence rather than fatigue.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          fixedDistanceKm: 3.5,
          structure: "Easy aerobic run",
          purpose: "Maintain the routine while reducing the load slightly.",
          executionTip: "Keep this smooth and relaxed.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          fixedDistanceKm: 3.2,
          structure: "10 min light steady inside an easy run",
          purpose: "Finish with a controlled rhythm touchpoint for general fitness.",
          executionTip: "The steady section should feel like comfortable focus, not a test.",
          workout: { kind: "EASY", blocks: [steadyBlock(10, 1, 0)] },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          fixedDistanceKm: 4.5,
          structure: "Reduced easy longer run",
          purpose: "Close the block with a comfortable endurance run.",
          executionTip: "Finish feeling ready to keep training next week.",
        },
      ],
    },
  ],
};

export default template;
