const easy = "easy";
const steady = "steady";
const tempo = "tempo";
const racePace = "race_pace";

const template = {
  id: "10k_beginner_8w_3run",
  metadata: {
    distance: "10K",
    level: "beginner",
    weeks: 8,
    runsPerWeek: 3,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      focus: "Build a calm three-run rhythm",
      coachNote: "Start with easy running only so the week feels repeatable before any faster work is added.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.34,
          structure: "Easy aerobic run",
          purpose: "Build consistency without adding fatigue.",
          executionTip: "Keep this relaxed enough that you could hold a full conversation.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.29,
          structure: "Short easy support run",
          purpose: "Add gentle frequency and make three runs per week feel normal.",
          executionTip: "Short and easy is the goal. Finish feeling better than when you started.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.37,
          structure: "Easy long run",
          purpose: "Begin building the endurance needed to cover 10K comfortably.",
          executionTip: "Run by effort and keep the final third controlled.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      focus: "Add relaxed strides without changing the effort of the week",
      coachNote: "A few short strides introduce leg speed while the week remains mostly easy.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.33,
          structure: "Easy aerobic run",
          purpose: "Continue building aerobic consistency.",
          executionTip: "Stay conversational and avoid drifting into steady effort.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.29,
          structure: "Easy run with 4 relaxed strides",
          purpose: "Improve running economy without creating workout-level fatigue.",
          executionTip: "Strides are smooth and relaxed, not sprints.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.38,
          structure: "Easy long run",
          purpose: "Gradually extend endurance while keeping the load manageable.",
          executionTip: "Keep the pace easy enough that you could add a few minutes if needed.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      focus: "Introduce gentle tempo in short controlled blocks",
      coachNote: "The first quicker session is short and controlled so it supports confidence rather than creating strain.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.32,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume steady before the first gentle tempo session.",
          executionTip: "Stay relaxed and leave the faster running for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: tempo,
          targetShare: 0.29,
          structure: "2 x 5 min gentle tempo with easy jog recovery",
          purpose: "Introduce controlled sustained running without aggressive interval work.",
          executionTip: "Comfortably hard only. You should finish each rep feeling in control.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 300, intensity: "TEMPO", intensityKey: "tempo" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.39,
          structure: "Easy long run",
          purpose: "Build confidence over a longer relaxed effort.",
          executionTip: "Keep it smooth and avoid pushing just because the distance is growing.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      focus: "Absorb the first build with an easier week",
      coachNote: "This week reduces strain so the next block can build from a fresher place.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.35,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while lowering training stress.",
          executionTip: "Err on the easy side and keep cadence relaxed.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.28,
          structure: "Easy-to-steady progression run",
          purpose: "Keep a little rhythm without making the deload hard.",
          executionTip: "Only progress to steady if the run feels comfortable.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 600, intensity: "EASY", intensityKey: "easy" },
                  { sec: 300, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.37,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while protecting recovery.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      focus: "Extend gentle tempo and keep the long run easy",
      coachNote: "The tempo block grows slightly, but the overall week stays controlled and beginner-friendly.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.31,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the longer tempo session.",
          executionTip: "Keep it smooth and avoid adding extra pace.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: tempo,
          targetShare: 0.30,
          structure: "2 x 8 min gentle tempo with easy jog recovery",
          purpose: "Build sustainable 10K support fitness without aggressive intervals.",
          executionTip: "Stay patient. The goal is even rhythm, not speed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 480, intensity: "TEMPO", intensityKey: "tempo" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.39,
          structure: "Easy long run",
          purpose: "Continue the long-run build while the quality remains controlled.",
          executionTip: "Keep this aerobic; the tempo session is the faster work for the week.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      focus: "Practise steady control with a stronger long run",
      coachNote: "This is the highest-support week, with one gentle continuous tempo and a confident easy long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.31,
          structure: "Easy run with 4 relaxed strides",
          purpose: "Refresh leg speed while keeping the run mostly easy.",
          executionTip: "Keep the strides light and stop them if mechanics get tight.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "quality",
          type: "TEMPO",
          target: tempo,
          targetShare: 0.29,
          structure: "15 min continuous gentle tempo",
          purpose: "Build confidence holding a controlled rhythm before taper begins.",
          executionTip: "Start slightly easier than you think and settle into a smooth effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 300, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 600, intensity: "TEMPO", intensityKey: "tempo" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.40,
          structure: "Easy long run",
          purpose: "Build endurance and confidence close to the demands of 10K.",
          executionTip: "Stay relaxed and let the distance be the stimulus.",
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "TAPER",
      focus: "Freshen up while keeping gentle 10K rhythm",
      coachNote: "The workload drops while one short controlled rhythm session keeps the legs prepared.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.34,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support without adding fatigue.",
          executionTip: "This should feel lighter than the previous build weeks.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.27,
          structure: "3 x 4 min controlled 10K effort with easy jog recovery",
          purpose: "Practise race rhythm in short controlled pieces without a hard interval load.",
          executionTip: "Keep this smooth and confidence-building. Do not chase faster-than-goal effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 240, intensity: "10K", intensityKey: "racepace" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.39,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while lowering fatigue before race week.",
          executionTip: "Shorter and easier is the point. Do not make up distance.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "TAPER",
      focus: "Stay fresh and complete the 10K effort",
      coachNote: "Race week keeps the legs moving, then protects freshness for the timed 10K effort.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.23,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Very short easy run with 4 relaxed strides",
          purpose: "Keep the legs responsive while staying fresh.",
          executionTip: "Skip the strides if anything feels tight or tired.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "race",
          type: "RACE",
          target: racePace,
          targetShare: 0.60,
          fixedDistanceKm: 10,
          structure: "Race day or timed 10K effort",
          purpose: "Complete the 10K with controlled pacing and confidence.",
          executionTip: "Start comfortable, settle into rhythm, and only press if you feel strong late.",
        },
      ],
    },
  ],
};

export default template;
