const threshold = "threshold";
const tenKEffort = "10k_effort";
const easy = "easy";
const racePace = "race_pace";

const template = {
  id: "10k_intermediate_8w_3run",
  metadata: {
    distance: "10K",
    level: "intermediate",
    weeks: 8,
    runsPerWeek: 3,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      focus: "Set the rhythm with controlled threshold work",
      coachNote: "Start with a repeatable week: one relaxed aerobic run, one threshold session, and one steady long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.38,
          structure: "Easy aerobic run",
          purpose: "Build aerobic volume without adding fatigue.",
          executionTip: "Keep this genuinely comfortable and finish feeling fresh.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.30,
          structure: "3 x 6 min threshold with easy jog recoveries",
          purpose: "Improve sustainable speed before introducing harder 10K-specific work.",
          executionTip: "Stay controlled. The reps should feel strong but repeatable.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 360, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          structure: "Easy long run",
          purpose: "Extend endurance while keeping the week balanced.",
          executionTip: "Run by effort and avoid pushing the final third.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      focus: "Add strides and lengthen threshold rhythm",
      coachNote: "This week adds light neuromuscular speed while keeping the main quality session aerobic.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.37,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Maintain aerobic volume and improve running economy.",
          executionTip: "Strides are quick and relaxed, not sprints.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.31,
          structure: "2 x 10 min threshold with easy jog recovery",
          purpose: "Build longer controlled efforts close to 10K support intensity.",
          executionTip: "Hold the same effort through both reps; avoid racing the second one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 600, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          structure: "Easy long run",
          purpose: "Consolidate endurance with slightly more time on feet.",
          executionTip: "Keep the pace relaxed enough that you could add a few minutes if needed.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      focus: "Introduce 10K effort in short controlled blocks",
      coachNote: "The first 10K-specific session uses time-based reps so effort stays smooth and manageable.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.38,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic load consistent before the 10K-effort workout.",
          executionTip: "Stay conversational and leave the faster work for the quality day.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: tenKEffort,
          targetShare: 0.30,
          structure: "5 x 3 min at 10K effort with easy jog recoveries",
          purpose: "Build familiarity with 10K effort without excessive intensity.",
          executionTip: "Think controlled race rhythm. Each rep should start slightly restrained.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_TIME",
                repeatCount: 5,
                workSec: 180,
                recoverSec: 120,
                intensity: "10K",
                intensityKey: "racepace",
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          structure: "Easy long run",
          purpose: "Support 10K performance with a stronger endurance base.",
          executionTip: "Keep the effort even from start to finish.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      focus: "Absorb the first build with lighter quality",
      coachNote: "Volume and intensity come down so the next block can progress without carrying fatigue.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.44,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while reducing load.",
          executionTip: "Err on the easy side and keep cadence relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: threshold,
          targetShare: 0.25,
          structure: "Light progression tempo",
          purpose: "Keep rhythm without accumulating heavy threshold fatigue.",
          executionTip: "Progress gradually. The finish should feel controlled, not forced.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 360, intensity: "STEADY" },
                  { sec: 360, intensity: "TEMPO" },
                  { sec: 240, intensity: "THRESHOLD" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.31,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while protecting recovery.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "SPECIFIC",
      focus: "Move into controlled 10K-specific distance reps",
      coachNote: "The main session now uses kilometre reps to make 10K rhythm more concrete.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.38,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the first controlled kilometre-rep session.",
          executionTip: "Keep it smooth and avoid adding extra intensity.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: tenKEffort,
          targetShare: 0.30,
          structure: "4 x 1 km controlled at 10K effort with jog recoveries",
          purpose: "Develop race-specific rhythm and pacing discipline.",
          executionTip: "Run the first rep like you could complete five. Controlled beats heroic.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 4,
                workM: 1000,
                intensity: "10K",
                intensityKey: "racepace",
                recover: { type: "TIME", sec: 120 },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          structure: "Easy long run",
          purpose: "Maintain endurance as race-specific work increases.",
          executionTip: "Keep this aerobic; the quality session is the priority.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "SPECIFIC",
      focus: "Blend threshold strength with a steady long-run finish",
      coachNote: "This is the peak support week: controlled threshold work plus a long run that finishes steady.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.36,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Refresh leg speed before the final specific push.",
          executionTip: "Keep the strides light and stop them if mechanics get tight.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.30,
          structure: "3 x 8 min threshold with easy jog recoveries",
          purpose: "Raise sustainable speed while keeping the session aerobic enough to recover from.",
          executionTip: "Hold back early. The final rep should be your best-controlled rep.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 480, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.34,
          structure: "Long run with steady finish",
          purpose: "Build endurance and controlled fatigue resistance for the final kilometres of a 10K.",
          executionTip: "Only lift to steady in the final portion if the run still feels controlled.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "TAPER",
      focus: "Sharpen 10K rhythm while reducing long-run load",
      coachNote: "This week keeps race rhythm present but trims the long run so freshness starts to build.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.41,
          structure: "Easy aerobic run",
          purpose: "Keep frequency and aerobic support without adding fatigue.",
          executionTip: "This should feel lighter than the previous build weeks.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: tenKEffort,
          targetShare: 0.30,
          structure: "3 x 1 mile at 10K effort with jog recoveries",
          purpose: "Rehearse sustained 10K rhythm in race-specific chunks.",
          executionTip: "Keep the effort even. Do not chase faster-than-goal work.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 3,
                workM: 1609,
                intensity: "10K",
                intensityKey: "racepace",
                recover: { type: "TIME", sec: 150 },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.29,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while lowering fatigue before race week.",
          executionTip: "Shorter and easier is the point. Do not make up distance.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "TAPER",
      focus: "Freshen up and race",
      coachNote: "Race week keeps touch with speed, then protects freshness for the 10K.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.29,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: racePace,
          targetShare: 0.18,
          structure: "6 x 1 min sharp but relaxed with full easy recoveries",
          purpose: "Wake up race rhythm without a heavy workout load.",
          executionTip: "Fast-but-smooth only. Stop before it becomes a test.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_TIME",
                repeatCount: 6,
                workSec: 60,
                recoverSec: 90,
                intensity: "10K",
                intensityKey: "racepace",
              },
            ],
          },
        },
        {
          role: "race",
          type: "RACE",
          target: racePace,
          targetShare: 0.53,
          fixedDistanceKm: 10,
          structure: "Race day 10K",
          purpose: "Execute the goal race with controlled pacing.",
          executionTip: "Start composed, settle into rhythm, and race the final third.",
        },
      ],
    },
  ],
};

export default template;
