const easy = "easy";
const steady = "steady";
const threshold = "threshold";
const fiveKEffort = "5k_effort";
const controlledVo2 = "vo2_controlled";
const racePace = "race_pace";

const template = {
  id: "5k_advanced_8w_5run",
  metadata: {
    distance: "5K",
    level: "advanced",
    weeks: 8,
    runsPerWeek: 5,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      focus: "Establish five-run rhythm with threshold strength",
      coachNote: "Start with controlled threshold work, easy frequency, strides, recovery, and a relaxed long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy aerobic run",
          purpose: "Build aerobic volume without adding fatigue.",
          executionTip: "Keep this genuinely easy so the threshold session stays high quality.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.19,
          structure: "4 x 6 min threshold with easy jog recoveries",
          purpose: "Build sustainable speed before harder 5K-specific work.",
          executionTip: "Stay controlled and make the final rep the smoothest one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 360, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Support running economy without creating another hard day.",
          executionTip: "Float the strides with relaxed form and full recovery.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Recovery run",
          purpose: "Add frequency while absorbing the quality session.",
          executionTip: "Keep this very relaxed and short enough to feel restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          structure: "Easy long run",
          purpose: "Maintain endurance as the 5K-specific block begins.",
          executionTip: "Run by effort and keep the final third comfortable.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      focus: "Introduce controlled VO2 with longer reps",
      coachNote: "This adds faster running through controlled 800m reps rather than random sprint work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support steady before the faster session.",
          executionTip: "Stay conversational and avoid drifting into steady effort.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: controlledVo2,
          targetShare: 0.19,
          structure: "5 x 800 m controlled VO2 with jog recoveries",
          purpose: "Build speed reserve for 5K pace without all-out repetition work.",
          executionTip: "Controlled fast running only. Stop the rep before form tightens.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 5,
                workM: 800,
                intensity: "5K",
                intensityKey: "interval",
                recover: { type: "TIME", sec: 150 },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Keep mechanics sharp while the week remains aerobic outside the workout.",
          executionTip: "Strides should feel quick, loose, and low pressure.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Recovery run",
          purpose: "Absorb the controlled VO2 work without stacking fatigue.",
          executionTip: "Run softer than normal if your legs feel heavy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          structure: "Easy long run",
          purpose: "Extend endurance while keeping the week balanced.",
          executionTip: "Keep this aerobic and do not turn it into a progression run.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      focus: "Move into concrete 5K race-pace reps",
      coachNote: "Kilometre reps make 5K rhythm more specific while staying controlled.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume consistent before 5K-specific work.",
          executionTip: "Keep it relaxed and leave the controlled effort for the quality day.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: fiveKEffort,
          targetShare: 0.20,
          structure: "5 x 1 km at 5K effort with jog recoveries",
          purpose: "Develop race-specific rhythm and pacing discipline.",
          executionTip: "Run the first rep like you could complete six. Controlled beats forced.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 5,
                workM: 1000,
                intensity: "5K",
                intensityKey: "interval",
                recover: { type: "TIME", sec: 150 },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.15,
          structure: "Steady aerobic support run",
          purpose: "Add controlled aerobic strength without adding a second hard workout.",
          executionTip: "Stay below threshold. Smooth and sustainable is the aim.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Recovery run",
          purpose: "Keep frequency high while letting the main session settle.",
          executionTip: "Keep cadence light and effort low.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.35,
          structure: "Long run with steady finish",
          purpose: "Build endurance and controlled fatigue resistance for the final kilometre of a 5K.",
          executionTip: "Only lift to steady in the last portion if the run remains controlled.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      focus: "Absorb the first build with lighter rhythm",
      coachNote: "Volume and intensity step down so the next specific block can progress from a fresher base.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while lowering training stress.",
          executionTip: "Err on the easy side and avoid adding pace.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: threshold,
          targetShare: 0.18,
          structure: "Controlled progression tempo",
          purpose: "Keep rhythm present without a heavy threshold load.",
          executionTip: "Progress gradually and finish feeling like you could do more.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 420, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 420, intensity: "TEMPO", intensityKey: "tempo" },
                  { sec: 240, intensity: "THRESHOLD", intensityKey: "threshold" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Keep leg speed lightly touched during the deload.",
          executionTip: "Relaxed strides only. Skip them if you feel flat.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.14,
          structure: "Short recovery run",
          purpose: "Keep frequency without adding load.",
          executionTip: "Short, soft, and easy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while protecting recovery.",
          executionTip: "Finish fresher than usual; this is a consolidation long run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "SPECIFIC",
      focus: "Extend 5K rhythm in longer race-pace blocks",
      coachNote: "This is the first peak-specific session, using 1200m reps to make race rhythm durable.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the longer race-pace rep session.",
          executionTip: "Keep it smooth and relaxed.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: fiveKEffort,
          targetShare: 0.20,
          structure: "4 x 1200 m at 5K effort with jog recoveries",
          purpose: "Build sustained race-pace strength in controlled blocks.",
          executionTip: "Start each rep composed. The final 400m should be strong, not desperate.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 4,
                workM: 1200,
                intensity: "5K",
                intensityKey: "interval",
                recover: { type: "TIME", sec: 180 },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.15,
          structure: "Steady aerobic support run",
          purpose: "Add aerobic strength while keeping the quality session as the priority.",
          executionTip: "Keep this controlled and below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Recovery run",
          purpose: "Absorb the 5K-specific workout.",
          executionTip: "Use effort, not pace, and keep the run restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          structure: "Easy long run",
          purpose: "Maintain endurance while race-specific work increases.",
          executionTip: "Keep this aerobic; the reps are the demanding work this week.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "SPECIFIC",
      focus: "Touch controlled VO2 without sprinting",
      coachNote: "A second controlled 800m session maintains speed reserve without turning the week into sprint work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume steady before the controlled VO2 session.",
          executionTip: "Stay easy and protect freshness.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: controlledVo2,
          targetShare: 0.20,
          structure: "6 x 800 m controlled VO2 with jog recoveries",
          purpose: "Maintain speed reserve without all-out repetition work.",
          executionTip: "Consistent reps matter more than squeezing the pace down.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 6,
                workM: 800,
                intensity: "5K",
                intensityKey: "interval",
                recover: { type: "TIME", sec: 150 },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Keep mechanics sharp without adding more fatigue.",
          executionTip: "Fast-but-relaxed only; stop if form tightens.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Recovery run",
          purpose: "Keep frequency while absorbing the faster reps.",
          executionTip: "Run softer than normal and keep this short.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.35,
          structure: "Long run with steady finish",
          purpose: "Build endurance and resilience for racing hard after sustained work.",
          executionTip: "Only finish steady if the long run still feels controlled.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "TAPER",
      focus: "Reduce load while rehearsing 5K rhythm",
      coachNote: "Volume drops, but one controlled race-rhythm session keeps 5K pace familiar.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support while tapering.",
          executionTip: "This should feel lighter than the peak weeks.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: fiveKEffort,
          targetShare: 0.18,
          structure: "3 x 1 km at 5K effort with jog recoveries",
          purpose: "Rehearse sustained 5K rhythm while reducing total load.",
          executionTip: "Keep it controlled and avoid racing the reps.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 3,
                workM: 1000,
                intensity: "5K",
                intensityKey: "interval",
                recover: { type: "TIME", sec: 150 },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy run with 5 relaxed strides",
          purpose: "Keep mechanics sharp without adding fatigue.",
          executionTip: "Keep the strides relaxed and stop before they feel demanding.",
          meta: { includeStrides: true, strides: 5 },
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run",
          purpose: "Keep frequency while the taper lowers fatigue.",
          executionTip: "Short and easy. Do not make up volume.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while freshness builds.",
          executionTip: "Shorter and easier is the point this week.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "TAPER",
      focus: "Freshen up and complete the 5K effort",
      coachNote: "Race week uses a short sharpener, keeps easy frequency, and protects freshness for the 5K.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.14,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: racePace,
          targetShare: 0.12,
          structure: "6 x 1 min sharp but relaxed with full easy recoveries",
          purpose: "Wake up race rhythm without a heavy workout load.",
          executionTip: "Fast-but-smooth only. Stop before it becomes a test.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_TIME",
                repeatCount: 6,
                workSec: 60,
                recoverSec: 90,
                intensity: "5K",
                intensityKey: "interval",
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.10,
          structure: "Very short easy run",
          purpose: "Keep the legs moving while staying fresh.",
          executionTip: "Easy only. Skip this if you feel flat or sore.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.08,
          structure: "Short shakeout run",
          purpose: "Stay loose before the 5K without adding training load.",
          executionTip: "Keep it short and relaxed with no extra work.",
        },
        {
          role: "race",
          type: "RACE",
          target: racePace,
          targetShare: 0.56,
          fixedDistanceKm: 5,
          structure: "Race day or timed 5K effort",
          purpose: "Execute the 5K with controlled pacing and a strong final kilometre.",
          executionTip: "Start composed, settle into rhythm, and race decisively after halfway.",
        },
      ],
    },
  ],
};

export default template;
