const easy = "easy";
const steady = "steady";
const tempo = "tempo";
const racePace = "race_pace";

const template = {
  id: "5k_beginner_8w_3run",
  metadata: {
    distance: "5K",
    level: "beginner",
    weeks: 8,
    runsPerWeek: 3,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      focus: "Build a calm three-run habit",
      coachNote: "Start with easy running only so the week feels repeatable before adding faster work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.35,
          structure: "Easy aerobic run",
          purpose: "Build running consistency without adding fatigue.",
          executionTip: "Keep this relaxed enough that you could hold a full conversation.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.29,
          structure: "Short easy support run",
          purpose: "Make three runs per week feel normal and manageable.",
          executionTip: "Short and easy is the goal. Finish feeling better than when you started.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.36,
          structure: "Easy long run",
          purpose: "Begin extending endurance for a comfortable 5K effort.",
          executionTip: "Run by effort and keep the final third controlled.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      focus: "Add relaxed strides without changing the week load",
      coachNote: "A few short strides introduce leg speed while the week remains mostly easy.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.34,
          structure: "Easy aerobic run",
          purpose: "Continue building aerobic consistency.",
          executionTip: "Stay conversational and avoid drifting into steady effort.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.29,
          structure: "Easy run with 4 relaxed strides",
          purpose: "Improve running economy without creating workout-level fatigue.",
          executionTip: "Strides are smooth and relaxed, not sprints.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.37,
          structure: "Easy long run",
          purpose: "Gradually extend endurance while keeping the load manageable.",
          executionTip: "Keep the pace easy enough that you could add a few minutes if needed.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      focus: "Introduce short controlled efforts",
      coachNote: "The first quicker running is short and controlled, more about rhythm than speed.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.33,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume steady before the first controlled-effort session.",
          executionTip: "Stay relaxed and leave the quicker running for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: tempo,
          targetShare: 0.29,
          structure: "4 x 2 min controlled effort with easy jog recovery",
          purpose: "Introduce faster rhythm without aggressive interval work.",
          executionTip: "Controlled and smooth only. Finish each rep feeling like you could do one more.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 120, intensity: "TEMPO", intensityKey: "tempo" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.38,
          structure: "Easy long run",
          purpose: "Build confidence over a longer relaxed effort.",
          executionTip: "Keep it smooth and avoid pushing just because the distance is growing.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      focus: "Absorb the first build with an easier week",
      coachNote: "This week reduces strain so the next block can build from a fresher place.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.36,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while lowering training stress.",
          executionTip: "Err on the easy side and keep cadence relaxed.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.28,
          structure: "Easy-to-steady progression run",
          purpose: "Keep a little rhythm without making the deload hard.",
          executionTip: "Only progress to steady if the run feels comfortable.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 480, intensity: "EASY", intensityKey: "easy" },
                  { sec: 240, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.36,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while protecting recovery.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      focus: "Extend controlled rhythm while staying beginner-safe",
      coachNote: "The controlled efforts grow slightly, but the week remains conservative and aerobic.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.33,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the controlled effort session.",
          executionTip: "Keep it smooth and avoid adding extra pace.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: tempo,
          targetShare: 0.30,
          structure: "5 x 2 min controlled effort with easy jog recovery",
          purpose: "Build confidence changing rhythm without hard interval stress.",
          executionTip: "Stay patient. The goal is repeatable form, not speed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 5,
                work: { valueSec: 120, intensity: "TEMPO", intensityKey: "tempo" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.37,
          structure: "Easy long run",
          purpose: "Continue the long-run build while the quality remains controlled.",
          executionTip: "Keep this aerobic; the controlled efforts are the quicker work for the week.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      focus: "Practise steady control with light strides",
      coachNote: "This is the strongest support week, using a short controlled tempo and light strides.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.33,
          structure: "Easy run with 4 relaxed strides",
          purpose: "Refresh leg speed while keeping the run mostly easy.",
          executionTip: "Keep the strides light and stop them if mechanics get tight.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "quality",
          type: "TEMPO",
          target: tempo,
          targetShare: 0.29,
          structure: "10 min continuous controlled tempo",
          purpose: "Build confidence holding a smooth controlled rhythm before taper begins.",
          executionTip: "Start slightly easier than you think and settle into a steady rhythm.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 240, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 360, intensity: "TEMPO", intensityKey: "tempo" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.38,
          structure: "Easy long run",
          purpose: "Build endurance and confidence close to the demands of 5K.",
          executionTip: "Stay relaxed and let the distance be the stimulus.",
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "TAPER",
      focus: "Freshen up while keeping controlled 5K rhythm",
      coachNote: "The workload drops while one short controlled rhythm session keeps the legs prepared.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.35,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support without adding fatigue.",
          executionTip: "This should feel lighter than the previous build weeks.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.27,
          structure: "4 x 90 sec controlled 5K rhythm with easy jog recovery",
          purpose: "Practise 5K rhythm in short controlled pieces without a hard interval load.",
          executionTip: "Keep this smooth and confidence-building. Do not chase faster-than-goal effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 90, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.38,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while lowering fatigue before race week.",
          executionTip: "Shorter and easier is the point. Do not make up distance.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "TAPER",
      focus: "Stay fresh and complete the 5K effort",
      coachNote: "Race week keeps the legs moving, then protects freshness for the timed 5K effort.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.28,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Very short easy run with 4 relaxed strides",
          purpose: "Keep the legs responsive while staying fresh.",
          executionTip: "Skip the strides if anything feels tight or tired.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "race",
          type: "RACE",
          target: racePace,
          targetShare: 0.55,
          fixedDistanceKm: 5,
          structure: "Race day or timed 5K effort",
          purpose: "Complete the 5K with controlled pacing and confidence.",
          executionTip: "Start comfortable, settle into rhythm, and only press if you feel strong late.",
        },
      ],
    },
  ],
};

export default template;
