const easy = "easy";
const steady = "steady";
const threshold = "threshold";
const fiveKEffort = "5k_effort";
const controlledVo2 = "vo2_controlled";
const racePace = "race_pace";

const template = {
  id: "5k_intermediate_8w_4run",
  metadata: {
    distance: "5K",
    level: "intermediate",
    weeks: 8,
    runsPerWeek: 4,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      focus: "Build threshold control and four-run rhythm",
      coachNote: "Start with controlled threshold work, easy frequency, relaxed strides, and a steady long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.24,
          structure: "Easy aerobic run",
          purpose: "Build aerobic volume without adding fatigue.",
          executionTip: "Keep this genuinely easy so the threshold session stays controlled.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.26,
          structure: "3 x 6 min threshold with easy jog recoveries",
          purpose: "Build sustainable speed before harder 5K-specific work.",
          executionTip: "Stay controlled. The reps should feel strong but repeatable.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 360, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Improve running economy without creating another hard day.",
          executionTip: "Strides are quick and relaxed, not sprints.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          structure: "Easy long run",
          purpose: "Support 5K performance with a stronger aerobic base.",
          executionTip: "Run by effort and avoid pushing the final third.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      focus: "Introduce controlled 5K effort by time",
      coachNote: "The first 5K-specific workout uses time-based reps so effort stays smooth rather than sprint-like.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.24,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support steady before the first 5K-effort session.",
          executionTip: "Stay conversational and leave the faster running for the quality day.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: fiveKEffort,
          targetShare: 0.27,
          structure: "6 x 2 min at 5K effort with easy jog recoveries",
          purpose: "Introduce 5K rhythm without relying on random sprint work.",
          executionTip: "Think controlled race rhythm. Each rep should start slightly restrained.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_TIME",
                repeatCount: 6,
                workSec: 120,
                recoverSec: 120,
                intensity: "5K",
                intensityKey: "interval",
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy support run",
          purpose: "Add frequency while keeping the week balanced.",
          executionTip: "Keep this relaxed enough to recover well from the workout.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.31,
          structure: "Easy long run",
          purpose: "Extend endurance while 5K-specific work begins.",
          executionTip: "Keep the effort even from start to finish.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      focus: "Lengthen threshold strength",
      coachNote: "Longer threshold reps build the aerobic support needed to hold 5K effort late in the race.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.23,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume consistent before longer threshold work.",
          executionTip: "Relax and keep the quality for the workout day.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.27,
          structure: "2 x 10 min threshold with easy jog recovery",
          purpose: "Build controlled sustained speed without excessive intensity.",
          executionTip: "Hold the same effort through both reps; avoid racing the second one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 600, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady aerobic support run",
          purpose: "Add controlled aerobic strength without making a second hard session.",
          executionTip: "Stay below threshold. Smooth and sustainable is the aim.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          structure: "Easy long run",
          purpose: "Maintain endurance as the quality load grows.",
          executionTip: "Keep this aerobic; the threshold session is the priority.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      focus: "Absorb the first build with lighter rhythm",
      coachNote: "Volume and intensity come down so the next specific block can progress without carrying fatigue.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.27,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while reducing load.",
          executionTip: "Err on the easy side and keep cadence relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: threshold,
          targetShare: 0.23,
          structure: "Light progression tempo",
          purpose: "Keep rhythm without accumulating heavy threshold fatigue.",
          executionTip: "Progress gradually. The finish should feel controlled, not forced.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 300, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 300, intensity: "TEMPO", intensityKey: "tempo" },
                  { sec: 180, intensity: "THRESHOLD", intensityKey: "threshold" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Keep leg speed lightly touched during the deload.",
          executionTip: "Relaxed strides only. Skip them if you feel flat.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.30,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while protecting recovery.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "SPECIFIC",
      focus: "Move into controlled 5K-specific distance reps",
      coachNote: "The main session now uses 800m reps to make 5K rhythm concrete without sprinting.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.23,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the first controlled 5K distance-rep session.",
          executionTip: "Keep it smooth and avoid adding extra intensity.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: fiveKEffort,
          targetShare: 0.29,
          structure: "5 x 800 m at 5K effort with jog recoveries",
          purpose: "Develop race-specific rhythm and pacing discipline.",
          executionTip: "Run the first rep like you could complete six. Controlled beats forced.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 5,
                workM: 800,
                intensity: "5K",
                intensityKey: "interval",
                recover: { type: "TIME", sec: 120 },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy run with 6 relaxed strides",
          purpose: "Keep frequency and maintain light leg speed.",
          executionTip: "Float the strides with relaxed form and full control.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.30,
          structure: "Easy long run",
          purpose: "Maintain endurance as race-specific work increases.",
          executionTip: "Keep this aerobic; the quality session is the demanding work.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "SPECIFIC",
      focus: "Touch controlled VO2 with short reps",
      coachNote: "Short VO2 reps build speed reserve, but they stay controlled and repeatable rather than sprint-like.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.22,
          structure: "Easy aerobic run",
          purpose: "Maintain aerobic support before the controlled VO2 session.",
          executionTip: "Keep the run relaxed and leave the legs ready for quality.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: controlledVo2,
          targetShare: 0.29,
          structure: "8 x 400 m controlled VO2 with jog recoveries",
          purpose: "Build speed reserve for 5K pace without all-out sprint work.",
          executionTip: "Keep every rep smooth. If form tightens, back off rather than chasing pace.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 8,
                workM: 400,
                intensity: "5K",
                intensityKey: "interval",
                recover: { type: "TIME", sec: 90 },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady aerobic support run",
          purpose: "Build controlled aerobic strength without adding another hard day.",
          executionTip: "Stay smooth and aerobic. This should never feel like threshold.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.31,
          structure: "Long run with steady finish",
          purpose: "Build endurance and controlled fatigue resistance for the final kilometre of a 5K.",
          executionTip: "Only lift to steady in the final portion if the run still feels controlled.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "TAPER",
      focus: "Sharpen 5K rhythm while reducing long-run load",
      coachNote: "This week keeps race rhythm present but trims the long run so freshness starts to build.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.27,
          structure: "Easy aerobic run",
          purpose: "Keep frequency and aerobic support without adding fatigue.",
          executionTip: "This should feel lighter than the previous build weeks.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: fiveKEffort,
          targetShare: 0.27,
          structure: "3 x 1 km at 5K effort with jog recoveries",
          purpose: "Rehearse sustained 5K rhythm in race-specific chunks.",
          executionTip: "Keep the effort even. Do not chase faster-than-goal work.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_DISTANCE",
                reps: 3,
                workM: 1000,
                intensity: "5K",
                intensityKey: "interval",
                recover: { type: "TIME", sec: 150 },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Short easy run with 5 relaxed strides",
          purpose: "Keep the legs responsive while fatigue comes down.",
          executionTip: "Keep this deliberately easy and stop strides before they feel demanding.",
          meta: { includeStrides: true, strides: 5 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.28,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while lowering fatigue before race week.",
          executionTip: "Shorter and easier is the point. Do not make up distance.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "TAPER",
      focus: "Freshen up and complete the 5K effort",
      coachNote: "Race week keeps touch with speed, then protects freshness for the timed 5K effort.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.22,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "INTERVALS",
          target: racePace,
          targetShare: 0.16,
          structure: "6 x 1 min sharp but relaxed with full easy recoveries",
          purpose: "Wake up race rhythm without a heavy workout load.",
          executionTip: "Fast-but-smooth only. Stop before it becomes a test.",
          workout: {
            kind: "INTERVALS",
            blocks: [
              {
                type: "REPEAT_TIME",
                repeatCount: 6,
                workSec: 60,
                recoverSec: 90,
                intensity: "5K",
                intensityKey: "interval",
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Very short easy shakeout",
          purpose: "Keep the legs loose while staying fresh for race day.",
          executionTip: "Keep it relaxed. Skip this if you feel unusually flat.",
        },
        {
          role: "race",
          type: "RACE",
          target: racePace,
          targetShare: 0.50,
          fixedDistanceKm: 5,
          structure: "Race day or timed 5K effort",
          purpose: "Execute the 5K with controlled pacing and a strong final kilometre.",
          executionTip: "Start composed, settle into rhythm, and race decisively after halfway.",
        },
      ],
    },
  ],
};

export default template;
