const easy = "easy";
const steady = "steady";
const threshold = "threshold";
const racePace = "race_pace";

const longRunCapKm = 23;

const template = {
  id: "half_advanced_12w_5run",
  metadata: {
    distance: "HALF",
    level: "advanced",
    weeks: 12,
    runsPerWeek: 5,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      loadMultiplier: 1,
      focus: "Establish five-run rhythm with threshold control",
      coachNote: "The first week sets easy frequency around one controlled threshold session, a steady support run, and an easy long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Build aerobic volume without adding intensity.",
          executionTip: "Keep this genuinely easy so the threshold session stays high quality.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "3 x 10 min threshold with easy jog recoveries",
          purpose: "Build sustainable aerobic strength for half-marathon performance.",
          executionTip: "Stay controlled and make the final rep the smoothest one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady medium-long run",
          purpose: "Add aerobic durability without turning the week into two hard workouts.",
          executionTip: "Keep this below threshold; smooth and sustainable is the aim.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Add frequency and relaxed mechanics while absorbing the main session.",
          executionTip: "Run very easy, then keep the strides loose and controlled.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.24,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Build durable endurance while the first week stays balanced.",
          executionTip: "Run by effort and keep the final third comfortable.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      loadMultiplier: 1.05,
      focus: "Introduce controlled half-marathon rhythm",
      coachNote: "The main session shifts to HM rhythm in repeatable blocks while the support run stays steady.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Maintain easy aerobic support before race-rhythm work.",
          executionTip: "Stay conversational and avoid drifting into steady effort.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.18,
          structure: "3 x 12 min half-marathon rhythm with easy jog recovery",
          purpose: "Build confidence locking into controlled half-marathon effort.",
          executionTip: "Patient and repeatable is the target; avoid forcing race pace.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 720, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady medium-long run",
          purpose: "Support aerobic durability while keeping the effort controlled.",
          executionTip: "Hold a smooth rhythm and stay comfortably below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Recovery run",
          purpose: "Keep frequency high while letting the HM-rhythm session absorb.",
          executionTip: "Run softer than normal if your legs feel heavy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.27,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Extend endurance without adding long-run intensity yet.",
          executionTip: "Keep the effort even and aerobic from start to finish.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      loadMultiplier: 1.1,
      focus: "Build longer threshold strength and long-run durability",
      coachNote: "Longer threshold reps and a steady-finish long run build the durability needed late in a half marathon.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume consistent before longer threshold work.",
          executionTip: "Relax and leave the controlled effort for the quality day.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.19,
          structure: "2 x 18 min threshold with easy jog recovery",
          purpose: "Build the ability to hold strong aerobic pressure for extended blocks.",
          executionTip: "Hold the same effort through both reps; do not force the second one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 1080, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady medium-long run",
          purpose: "Add controlled aerobic strength without adding a second hard workout.",
          executionTip: "Stay below threshold and keep the effort smooth.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Maintain mechanics while the larger threshold session settles.",
          executionTip: "Keep cadence light and strides relaxed, never forced.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.35,
          longRunCapKm,
          structure: "Long run with steady finish",
          purpose: "Build controlled fatigue resistance for the final miles of a half marathon.",
          executionTip: "Only lift to steady in the last portion if the run remains controlled.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      loadMultiplier: 0.88,
      focus: "Absorb the opening build",
      coachNote: "Volume and intensity step down so the next specific block starts from a fresher base.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while lowering training stress.",
          executionTip: "Err on the easy side and avoid adding pace.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.17,
          structure: "Controlled progression tempo",
          purpose: "Keep rhythm present without a heavy threshold load.",
          executionTip: "Progress gradually and finish feeling like you could do more.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 480, intensity: "TEMPO", intensityKey: "tempo" },
                  { sec: 300, intensity: "THRESHOLD", intensityKey: "threshold" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy medium-long run",
          purpose: "Preserve aerobic support without adding strain.",
          executionTip: "Keep this comfortably easy and do not chase normal medium-long pace.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.14,
          structure: "Short recovery run",
          purpose: "Keep five-run frequency while protecting the deload.",
          executionTip: "Short, soft, and easy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while recovery catches up.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      loadMultiplier: 1.14,
      focus: "Raise threshold volume",
      coachNote: "Threshold volume expands while the medium-long run keeps aerobic durability high.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the larger threshold session.",
          executionTip: "Keep it smooth and avoid adding extra intensity.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.19,
          structure: "4 x 10 min threshold with easy jog recoveries",
          purpose: "Build threshold volume for sustained half-marathon strength.",
          executionTip: "Repeatable pressure only. No single rep should feel heroic.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 600, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady medium-long run",
          purpose: "Add aerobic durability that complements threshold work.",
          executionTip: "Keep this smooth and never harder than steady.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Maintain light leg speed without adding another workout.",
          executionTip: "Float the strides and recover fully between them.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Continue the long-run build while threshold volume increases.",
          executionTip: "Keep this aerobic; the quality session is the main stress.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "SPECIFIC",
      loadMultiplier: 1.2,
      focus: "Blend threshold strength with HM pace confidence",
      coachNote: "This week adds direct HM-rhythm blocks while keeping the rest of the work aerobic.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support before the race-rhythm workout.",
          executionTip: "Stay relaxed and leave rhythm for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.19,
          structure: "4 x 12 min half-marathon rhythm with easy jog recoveries",
          purpose: "Build confidence holding goal rhythm in repeatable pieces.",
          executionTip: "Controlled from the first rep. Smooth matters more than fast.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 720, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Steady medium-long run",
          purpose: "Strengthen aerobic durability while staying below threshold.",
          executionTip: "Hold relaxed form and keep the effort sustainable.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run",
          purpose: "Keep frequency without stacking fatigue.",
          executionTip: "Easy enough that it helps the week, not adds to it.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.34,
          longRunCapKm,
          structure: "Long run with steady finish",
          purpose: "Build controlled endurance and late-run confidence.",
          executionTip: "Keep most of the run easy and finish steady only if controlled.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "BUILD",
      loadMultiplier: 1.26,
      focus: "Peak sustained threshold strength",
      coachNote: "This is a strong aerobic week: sustained threshold work, steady support, and a confident long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Easy aerobic run",
          purpose: "Keep easy volume present before the peak threshold session.",
          executionTip: "Stay relaxed and avoid adding pace.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.20,
          structure: "3 x 15 min threshold with easy jog recoveries",
          purpose: "Build sustained aerobic power for holding form deep into the race.",
          executionTip: "Keep the first rep controlled enough that the third is composed.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 900, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady medium-long run",
          purpose: "Add durable aerobic volume without turning the week into a second workout.",
          executionTip: "Stay smooth, patient, and below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep mechanics sharp while the workload peaks.",
          executionTip: "Keep the run very easy and the strides relaxed.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Extend endurance toward peak half-marathon preparation.",
          executionTip: "Keep this aerobic and controlled despite the bigger week.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "DELOAD",
      loadMultiplier: 1,
      focus: "Consolidate before the final specific block",
      coachNote: "A second deload protects adaptation before the peak HM-specific work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Relaxed deload easy run",
          purpose: "Absorb the previous build while maintaining routine.",
          executionTip: "Keep it light and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.17,
          structure: "2 x 10 min steady with easy jog recovery",
          purpose: "Keep rhythm present without heavy fatigue.",
          executionTip: "Stay controlled and finish fresher than normal.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 600, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy medium-long run",
          purpose: "Preserve aerobic support while reducing strain.",
          executionTip: "Keep this easier than your usual medium-long run.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.14,
          structure: "Short recovery run",
          purpose: "Keep five-run rhythm without adding load.",
          executionTip: "Short and restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Protect recovery before the final race-specific build.",
          executionTip: "Finish fresher than usual.",
        },
      ],
    },
    {
      weekNumber: 9,
      phase: "SPECIFIC",
      loadMultiplier: 1.32,
      focus: "Peak half-marathon pace confidence",
      coachNote: "This is the key specific week, with longer HM-rhythm work and the peak long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the key HM-rhythm workout.",
          executionTip: "Keep this truly easy and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.20,
          structure: "3 x 18 min half-marathon rhythm with easy jog recoveries",
          purpose: "Practise sustained race rhythm while keeping the work broken into manageable blocks.",
          executionTip: "Hold back early. The final rep should still feel composed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 1080, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability during the specific block.",
          executionTip: "Keep the rhythm smooth and avoid threshold effort.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep the legs responsive without adding fatigue.",
          executionTip: "Relaxed mechanics only; no sprinting.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Peak easy long run",
          purpose: "Build race confidence through the longest controlled aerobic effort.",
          executionTip: "Keep it aerobic from the start. The win is finishing in control.",
        },
      ],
    },
    {
      weekNumber: 10,
      phase: "SPECIFIC",
      loadMultiplier: 1.22,
      focus: "Rehearse long-run quality and controlled sharpening",
      coachNote: "The long run comes down slightly but adds controlled HM rhythm while the main workout sharpens threshold.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support present without adding fatigue.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "2 x 15 min threshold with easy jog recovery",
          purpose: "Sharpen sustainable rhythm before taper without a major overload.",
          executionTip: "Keep this controlled and slightly fresher than peak weeks.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 900, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Steady medium-long run",
          purpose: "Keep aerobic durability present while taper approaches.",
          executionTip: "Smooth and controlled; avoid forcing pace.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Recovery run",
          purpose: "Absorb the specific block without adding strain.",
          executionTip: "Very relaxed and restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: racePace,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Long run with 3 x 10 min half-marathon rhythm",
          purpose: "Rehearse race rhythm under controlled long-run fatigue.",
          executionTip: "Keep the HM-rhythm blocks smooth, then return to easy running.",
          workout: {
            kind: "LONG",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 300, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
      ],
    },
    {
      weekNumber: 11,
      phase: "TAPER",
      loadMultiplier: 0.8,
      focus: "Freshen up while keeping HM rhythm",
      coachNote: "Volume drops while one short HM-rhythm session and light strides preserve confidence.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support while fatigue falls.",
          executionTip: "This should feel lighter than the build weeks.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.17,
          structure: "3 x 8 min controlled half-marathon rhythm with easy jog recovery",
          purpose: "Rehearse race rhythm in short, fresh, confidence-building pieces.",
          executionTip: "Smooth and controlled only. Do not chase faster-than-goal effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 480, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Short steady support run",
          purpose: "Keep rhythm alive without adding heavy load.",
          executionTip: "Controlled only; stay fresher than normal.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.14,
          structure: "Short recovery run with 4 relaxed strides",
          purpose: "Stay loose without adding fatigue.",
          executionTip: "Keep the strides relaxed and stop well short of sprinting.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while building freshness for race week.",
          executionTip: "Shorter and easier is the correct execution.",
        },
      ],
    },
    {
      weekNumber: 12,
      phase: "TAPER",
      loadMultiplier: 0.62,
      focus: "Stay sharp and race the half marathon",
      coachNote: "Race week keeps easy rhythm early, adds a light HM-rhythm tune-up, then protects freshness for the half marathon.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.13,
          structure: "5 x 2 min relaxed half-marathon rhythm with easy jog recovery",
          purpose: "Prime race rhythm without creating workout-level fatigue.",
          executionTip: "Controlled and light. This is a confidence tune-up, not a test.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 5,
                work: { valueSec: 120, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.10,
          structure: "Very short easy shakeout",
          purpose: "Keep the legs moving while preserving freshness.",
          executionTip: "Keep this short and relaxed with no extra work.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.08,
          structure: "Optional recovery jog",
          purpose: "Stay loose only if it helps you feel fresher.",
          executionTip: "Skip this if freshness would be better served by rest.",
        },
        {
          role: "race",
          type: "RACE",
          target: racePace,
          targetShare: 0.54,
          fixedDistanceKm: 21.1,
          structure: "Half marathon race or timed 21.1K effort",
          purpose: "Execute the target half-marathon effort with controlled pacing.",
          executionTip: "Start patient, settle into rhythm, and aim to finish composed.",
          workout: {
            kind: "RACE",
            fixedDistanceKm: 21.1,
            label: "Half marathon race",
          },
        },
      ],
    },
  ],
};

export default template;
