const easy = "easy";
const steady = "steady";
const tempo = "tempo";
const racePace = "race_pace";

const longRunCapKm = 18;

const template = {
  id: "half_beginner_12w_3run",
  metadata: {
    distance: "HALF",
    level: "beginner",
    weeks: 12,
    runsPerWeek: 3,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      loadMultiplier: 1,
      focus: "Build a calm three-run half-marathon rhythm",
      coachNote: "Start with easy running only so the routine is repeatable before adding steady work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.32,
          structure: "Easy aerobic run",
          purpose: "Build consistency without adding fatigue.",
          executionTip: "Keep this relaxed enough that you could hold a full conversation.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.27,
          structure: "Short easy support run",
          purpose: "Add gentle frequency and make three runs per week feel normal.",
          executionTip: "Short and easy is the goal. Finish feeling better than when you started.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.41,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Begin building the endurance needed for a comfortable half marathon.",
          executionTip: "Run by effort and keep the final third controlled.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      loadMultiplier: 1.05,
      focus: "Extend easy durability",
      coachNote: "The week stays easy while the long run edges forward conservatively.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.31,
          structure: "Easy aerobic run",
          purpose: "Continue building aerobic consistency.",
          executionTip: "Stay conversational and avoid drifting into steady effort.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.27,
          structure: "Easy support run",
          purpose: "Keep frequency steady without increasing intensity.",
          executionTip: "Stay relaxed and keep the run controlled from start to finish.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.42,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Gradually extend endurance while keeping the load manageable.",
          executionTip: "Keep the pace easy enough that you could add a few minutes if needed.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      loadMultiplier: 1.1,
      focus: "Introduce light steady running",
      coachNote: "The first controlled work is steady rather than fast, building durability without interval stress.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.30,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume steady before the first steady session.",
          executionTip: "Stay relaxed and leave the controlled rhythm for the support day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.28,
          structure: "2 x 8 min steady with easy jog recovery",
          purpose: "Introduce light steady running for aerobic durability.",
          executionTip: "Controlled only. You should finish each rep feeling like you could do one more.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 480, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.42,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Build confidence over a longer relaxed effort.",
          executionTip: "Keep it smooth and avoid pushing just because the distance is growing.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      loadMultiplier: 0.9,
      focus: "Absorb the first endurance block",
      coachNote: "This deload lowers strain while preserving the routine.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.34,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while lowering training stress.",
          executionTip: "Err on the easy side and keep cadence relaxed.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.27,
          structure: "Easy-to-steady progression run",
          purpose: "Keep a little rhythm without making the deload hard.",
          executionTip: "Only progress to steady if the run feels comfortable.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 600, intensity: "EASY", intensityKey: "easy" },
                  { sec: 360, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.39,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while protecting recovery.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      loadMultiplier: 1.14,
      focus: "Resume long-run progression",
      coachNote: "The long run builds again, while weekday running stays controlled and aerobic.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.30,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the longer steady session.",
          executionTip: "Keep it smooth and avoid adding extra pace.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.28,
          structure: "2 x 10 min steady with easy jog recovery",
          purpose: "Build durable aerobic rhythm without aggressive intervals.",
          executionTip: "Stay patient. The goal is even rhythm, not speed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 600, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.42,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Continue the long-run build while weekday quality remains controlled.",
          executionTip: "Keep this aerobic; the steady session is the controlled work for the week.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      loadMultiplier: 1.2,
      focus: "Build aerobic durability",
      coachNote: "This week adds a little more steady rhythm while keeping the long run easy.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.29,
          structure: "Easy aerobic run",
          purpose: "Maintain aerobic support before the durability session.",
          executionTip: "Keep the run relaxed and controlled.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.29,
          structure: "20 min continuous steady run",
          purpose: "Build confidence holding a smooth aerobic rhythm.",
          executionTip: "Start slightly easier than you think and settle into steady effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.42,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Build endurance and confidence for the half-marathon distance.",
          executionTip: "Stay relaxed and let the distance be the stimulus.",
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "BUILD",
      loadMultiplier: 1.26,
      focus: "Extend long-run confidence",
      coachNote: "The long run continues its conservative build while weekday running remains steady and controlled.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.29,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume consistent before the steady support run.",
          executionTip: "Stay conversational and leave extra effort out of this run.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.28,
          structure: "Easy run with steady finish",
          purpose: "Build aerobic durability without turning the week into hard training.",
          executionTip: "Only finish steady if the early miles feel relaxed.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 900, intensity: "EASY", intensityKey: "easy" },
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.43,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Extend endurance while keeping the week beginner-safe.",
          executionTip: "Keep the final third controlled and avoid chasing pace.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "DELOAD",
      loadMultiplier: 1,
      focus: "Consolidate before the peak endurance block",
      coachNote: "A second deload keeps the 12-week build sustainable and lowers injury risk.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.34,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while absorbing the previous build.",
          executionTip: "Keep it light and avoid making up distance.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.27,
          structure: "Short easy-to-steady run",
          purpose: "Keep rhythm present without adding heavy load.",
          executionTip: "Stay controlled and stop at easy if steady does not feel natural.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 600, intensity: "EASY", intensityKey: "easy" },
                  { sec: 300, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.39,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while recovery catches up.",
          executionTip: "Finish fresher than usual; this prepares you for the final build.",
        },
      ],
    },
    {
      weekNumber: 9,
      phase: "SPECIFIC",
      loadMultiplier: 1.32,
      focus: "Peak endurance confidence",
      coachNote: "This is the biggest endurance-support week, with steady rhythm and a confident long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.28,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the longer steady session.",
          executionTip: "Keep it smooth and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.29,
          structure: "2 x 12 min steady with easy jog recovery",
          purpose: "Build aerobic durability for sustained half-marathon effort.",
          executionTip: "Stay controlled. The second rep should feel as smooth as the first.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 720, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.43,
          longRunCapKm,
          structure: "Peak easy long run",
          purpose: "Build race confidence through the longest relaxed effort of the plan.",
          executionTip: "Keep this aerobic from the start. The win is finishing controlled.",
        },
      ],
    },
    {
      weekNumber: 10,
      phase: "SPECIFIC",
      loadMultiplier: 1.24,
      focus: "Practise race confidence with steady finishing",
      coachNote: "The long run comes down slightly and includes optional steady rhythm to rehearse confidence.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.30,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume present without adding fatigue.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.27,
          structure: "Easy run with steady finish",
          purpose: "Practise controlled rhythm while taper is approaching.",
          executionTip: "Only lift to steady if the early run feels comfortable.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 900, intensity: "EASY", intensityKey: "easy" },
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.43,
          longRunCapKm,
          structure: "Long run with steady finish",
          purpose: "Build race confidence without making the long run aggressive.",
          executionTip: "Keep most of this easy; only finish steady if you feel controlled.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
        },
      ],
    },
    {
      weekNumber: 11,
      phase: "TAPER",
      loadMultiplier: 0.82,
      focus: "Freshen up while keeping rhythm",
      coachNote: "The workload drops so freshness can build while one short steady run maintains confidence.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.35,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support without adding fatigue.",
          executionTip: "This should feel lighter than the previous build weeks.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.27,
          structure: "3 x 5 min controlled half-marathon rhythm with easy jog recovery",
          purpose: "Rehearse race rhythm in short controlled pieces without a hard workout load.",
          executionTip: "Keep this smooth and confidence-building. Do not chase faster-than-goal effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 300, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.38,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while lowering fatigue before race week.",
          executionTip: "Shorter and easier is the point. Do not make up distance.",
        },
      ],
    },
    {
      weekNumber: 12,
      phase: "TAPER",
      loadMultiplier: 0.55,
      focus: "Stay fresh and complete the half marathon",
      coachNote: "Race week keeps the legs moving, then protects freshness for the half-marathon effort.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.14,
          structure: "Very short easy shakeout",
          purpose: "Keep the legs responsive while staying fresh.",
          executionTip: "Keep this short and relaxed with no extra work.",
        },
        {
          role: "race",
          type: "RACE",
          target: racePace,
          targetShare: 0.65,
          fixedDistanceKm: 21.1,
          structure: "Race day or timed half marathon effort",
          purpose: "Complete the half marathon with controlled pacing and confidence.",
          executionTip: "Start comfortable, settle into rhythm, and protect effort until the final third.",
        },
      ],
    },
  ],
};

export default template;
