const easy = "easy";
const steady = "steady";
const threshold = "threshold";
const racePace = "race_pace";

const longRunCapKm = 20;

const template = {
  id: "half_intermediate_12w_4run",
  metadata: {
    distance: "HALF",
    level: "intermediate",
    weeks: 12,
    runsPerWeek: 4,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      loadMultiplier: 1,
      focus: "Build a repeatable four-run rhythm with controlled threshold work",
      coachNote: "Start with aerobic frequency, one controlled threshold session, and an easy long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.22,
          structure: "Easy aerobic run",
          purpose: "Build weekly consistency without adding fatigue.",
          executionTip: "Keep this relaxed enough that the threshold session feels controlled.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.26,
          structure: "3 x 8 min threshold with easy jog recoveries",
          purpose: "Improve sustainable aerobic strength for half-marathon pacing.",
          executionTip: "Stay smooth and repeatable. The last rep should not feel like a race.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 480, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy support run with 6 relaxed strides",
          purpose: "Add low-stress frequency and keep leg speed relaxed.",
          executionTip: "Strides are relaxed and quick, not sprints.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Build durable endurance while the week stays balanced.",
          executionTip: "Run by effort and keep the final third controlled.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      loadMultiplier: 1.05,
      focus: "Extend aerobic durability",
      coachNote: "The quality stays threshold-based while the long run edges forward conservatively.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.22,
          structure: "Easy aerobic run",
          purpose: "Maintain easy volume before the longer controlled work.",
          executionTip: "Stay conversational and avoid drifting into steady effort.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.27,
          structure: "2 x 12 min threshold with easy jog recovery",
          purpose: "Build longer sustainable efforts that support half-marathon pace.",
          executionTip: "Hold the same effort through both reps; do not race the second one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 720, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Steady aerobic support run",
          purpose: "Add controlled aerobic durability without making a second hard day.",
          executionTip: "Keep this below threshold; smooth and sustainable is the aim.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Continue building time on feet with a controlled aerobic load.",
          executionTip: "Keep the effort even and avoid pushing the finish.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      loadMultiplier: 1.1,
      focus: "Introduce half-marathon rhythm in controlled pieces",
      coachNote: "Half-marathon rhythm appears in short blocks so the effort feels familiar without being draining.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the first race-rhythm workout.",
          executionTip: "Keep this easy and save rhythm for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.27,
          structure: "3 x 10 min half-marathon rhythm with easy jog recovery",
          purpose: "Build confidence locking into controlled half-marathon effort.",
          executionTip: "This should feel smooth, patient, and repeatable.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run",
          purpose: "Keep frequency high while allowing the race-rhythm work to absorb.",
          executionTip: "Short, relaxed, and deliberately easy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Extend endurance with a slightly longer aerobic run.",
          executionTip: "Keep this fully aerobic; the rhythm work is already done for the week.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      loadMultiplier: 0.9,
      focus: "Absorb the first threshold and rhythm block",
      coachNote: "The week pulls back volume and intensity while preserving four-run consistency.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.25,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while reducing training stress.",
          executionTip: "Err on the easy side and finish fresh.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.23,
          structure: "Light progression tempo",
          purpose: "Keep rhythm present without adding heavy threshold load.",
          executionTip: "Progress only if the legs feel good; controlled beats forced.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 480, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 360, intensity: "TEMPO", intensityKey: "tempo" },
                  { sec: 240, intensity: "THRESHOLD", intensityKey: "threshold" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Short easy support run",
          purpose: "Keep four-run frequency while protecting the deload.",
          executionTip: "Do not make up volume. Keep this relaxed.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.31,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while recovery catches up.",
          executionTip: "Shorter and easier is the point this week.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      loadMultiplier: 1.14,
      focus: "Resume the endurance build with longer threshold strength",
      coachNote: "Threshold work lengthens again, supported by easy volume and a controlled long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the longer threshold workout.",
          executionTip: "Keep it smooth and avoid adding extra pace.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.28,
          structure: "3 x 10 min threshold with easy jog recoveries",
          purpose: "Strengthen sustainable speed for the middle miles of a half marathon.",
          executionTip: "Keep each rep controlled from the start; no surging.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run with 6 relaxed strides",
          purpose: "Maintain frequency and relaxed mechanics.",
          executionTip: "Float the strides and recover fully between them.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Continue building endurance while threshold work progresses.",
          executionTip: "Keep this aerobic and even from start to finish.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      loadMultiplier: 1.2,
      focus: "Build continuous steady strength",
      coachNote: "A continuous steady session builds durability without resorting to short interval stress.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Easy aerobic run",
          purpose: "Maintain easy aerobic support before the steady session.",
          executionTip: "Relax and keep the effort comfortably easy.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.27,
          structure: "30 min continuous steady run",
          purpose: "Improve aerobic durability and confidence holding controlled rhythm.",
          executionTip: "Start slightly easier than steady and settle into a smooth rhythm.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 900, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 900, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Easy run with steady finish",
          purpose: "Add gentle aerobic strength without creating another hard session.",
          executionTip: "Keep most of this easy and only finish steady if it feels natural.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 900, intensity: "EASY", intensityKey: "easy" },
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Build time on feet while preserving control.",
          executionTip: "Let the duration do the work. Keep effort patient.",
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "BUILD",
      loadMultiplier: 1.26,
      focus: "Peak threshold durability",
      coachNote: "This is a stronger aerobic week, anchored by threshold work and a confident long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy aerobic run",
          purpose: "Keep the legs moving before the peak threshold session.",
          executionTip: "Stay relaxed and leave the work for the quality day.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.28,
          structure: "2 x 15 min threshold with easy jog recovery",
          purpose: "Build sustained aerobic power for holding form deep into the race.",
          executionTip: "Keep the first rep controlled enough that the second is just as smooth.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 900, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run",
          purpose: "Keep frequency high while protecting recovery from threshold work.",
          executionTip: "Short and conversational is enough.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Extend endurance toward peak half-marathon preparation.",
          executionTip: "Keep this aerobic and avoid chasing pace late.",
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "DELOAD",
      loadMultiplier: 1,
      focus: "Consolidate before the specific block",
      coachNote: "A second deload keeps the 12-week build sustainable before race-specific confidence work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.25,
          structure: "Relaxed deload easy run",
          purpose: "Absorb the threshold build while maintaining routine.",
          executionTip: "Keep it light and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.23,
          structure: "2 x 8 min steady with easy jog recovery",
          purpose: "Keep controlled rhythm present without heavy fatigue.",
          executionTip: "Stay under control and finish fresher than normal.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 480, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Short easy support run",
          purpose: "Keep frequency while reducing overall stress.",
          executionTip: "No extra distance this week.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.31,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Protect recovery before the final specific block.",
          executionTip: "Finish fresh and controlled.",
        },
      ],
    },
    {
      weekNumber: 9,
      phase: "SPECIFIC",
      loadMultiplier: 1.3,
      focus: "Build half-marathon pace confidence",
      coachNote: "The main workout now targets race rhythm more directly while the long run reaches peak support.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the key half-marathon rhythm session.",
          executionTip: "Keep this truly easy and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.28,
          structure: "3 x 12 min half-marathon rhythm with easy jog recovery",
          purpose: "Practise controlled race rhythm in repeatable blocks.",
          executionTip: "Hold back early. The final rep should still feel composed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 720, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run with 6 relaxed strides",
          purpose: "Maintain relaxed mechanics without adding fatigue.",
          executionTip: "Keep the strides light and controlled.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Peak easy long run",
          purpose: "Build race confidence through the longest controlled aerobic effort.",
          executionTip: "Keep it aerobic from the start. The win is finishing in control.",
        },
      ],
    },
    {
      weekNumber: 10,
      phase: "SPECIFIC",
      loadMultiplier: 1.22,
      focus: "Rehearse controlled finishing strength",
      coachNote: "The long run comes down slightly but includes controlled steady finishing to rehearse confidence.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support present without adding fatigue.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.27,
          structure: "2 x 12 min threshold with easy jog recovery",
          purpose: "Sharpen sustainable rhythm before taper without a major overload.",
          executionTip: "Keep this controlled and slightly fresher than peak weeks.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 720, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Easy run with steady finish",
          purpose: "Practise relaxed rhythm while taper approaches.",
          executionTip: "Keep most of the run easy; only finish steady if it feels controlled.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 900, intensity: "EASY", intensityKey: "easy" },
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.33,
          longRunCapKm,
          structure: "Long run with steady finish",
          purpose: "Build final race confidence without making the long run aggressive.",
          executionTip: "Keep most of this easy; only finish steady if you feel composed.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
        },
      ],
    },
    {
      weekNumber: 11,
      phase: "TAPER",
      loadMultiplier: 0.82,
      focus: "Freshen up while keeping half-marathon rhythm",
      coachNote: "Volume drops while one short race-rhythm workout keeps confidence high.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.25,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support while fatigue falls.",
          executionTip: "This should feel lighter than the build weeks.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.24,
          structure: "3 x 6 min controlled half-marathon rhythm with easy jog recovery",
          purpose: "Rehearse race rhythm in short, fresh, confidence-building pieces.",
          executionTip: "Smooth and controlled only. Do not chase faster-than-goal effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 360, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Short easy support run with 4 relaxed strides",
          purpose: "Stay loose without adding fatigue.",
          executionTip: "Keep the strides relaxed and stop well short of sprinting.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.31,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while building freshness for race week.",
          executionTip: "Shorter and easier is the correct execution.",
        },
      ],
    },
    {
      weekNumber: 12,
      phase: "TAPER",
      loadMultiplier: 0.58,
      focus: "Stay fresh and complete the half marathon",
      coachNote: "Race week keeps easy rhythm early, then protects freshness for the half-marathon effort.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: racePace,
          targetShare: 0.16,
          structure: "4 x 2 min relaxed half-marathon rhythm with easy jog recovery",
          purpose: "Prime race rhythm without creating workout-level fatigue.",
          executionTip: "Controlled and light. This is a confidence tune-up, not a test.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 120, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.10,
          structure: "Very short easy shakeout",
          purpose: "Keep the legs moving while preserving freshness.",
          executionTip: "Keep this short and relaxed with no extra work.",
        },
        {
          role: "race",
          type: "RACE",
          target: racePace,
          targetShare: 0.56,
          fixedDistanceKm: 21.1,
          structure: "Half marathon race or timed 21.1K effort",
          purpose: "Complete the target half-marathon effort with controlled pacing.",
          executionTip: "Start patient, settle into rhythm, and aim to finish composed.",
          workout: {
            kind: "RACE",
            fixedDistanceKm: 21.1,
            label: "Half marathon race",
          },
        },
      ],
    },
  ],
};

export default template;
