const easy = "easy";
const steady = "steady";
const threshold = "threshold";
const marathonPace = "race_pace";

const longRunCapKm = 36;

const template = {
  id: "marathon_advanced_18w_5run",
  metadata: {
    distance: "MARATHON",
    level: "advanced",
    weeks: 18,
    runsPerWeek: 5,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      loadMultiplier: 1,
      focus: "Establish advanced marathon rhythm",
      coachNote: "Start with easy volume, threshold support, a steady medium-long run, strides, and a controlled long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy aerobic run",
          purpose: "Build aerobic volume without adding intensity.",
          executionTip: "Keep this genuinely easy so the threshold session stays high quality.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "3 x 10 min threshold with easy jog recoveries",
          purpose: "Build sustainable aerobic strength that supports marathon pace.",
          executionTip: "Stay controlled and make the final rep the smoothest one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Add aerobic durability without making a second hard workout.",
          executionTip: "Keep this below threshold; smooth and sustainable is the aim.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Add frequency and relaxed mechanics while absorbing the main session.",
          executionTip: "Run very easy, then keep the strides loose and controlled.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.27,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Start the marathon long-run build from a controlled aerobic base.",
          executionTip: "Run by effort and keep the final third comfortable.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      loadMultiplier: 1.04,
      focus: "Extend threshold support and medium-long durability",
      coachNote: "Longer threshold support and a steady medium-long run keep the first block aerobic.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy aerobic run",
          purpose: "Maintain easy aerobic volume before the longer controlled work.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "2 x 15 min threshold with easy jog recovery",
          purpose: "Build longer sustainable efforts that support marathon economy.",
          executionTip: "Hold the same effort through both reps; avoid forcing the second one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 900, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Build aerobic durability while staying below threshold.",
          executionTip: "Smooth and patient. This should never feel like a workout.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run",
          purpose: "Keep frequency high while letting the quality work absorb.",
          executionTip: "Run softer than normal if your legs feel heavy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.30,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Gradually extend time on feet with controlled effort.",
          executionTip: "Keep the effort even and avoid pushing the finish.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      loadMultiplier: 1.08,
      focus: "Introduce marathon-rhythm blocks",
      coachNote: "Marathon rhythm appears in controlled blocks while the long run continues to build.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the first marathon-rhythm workout.",
          executionTip: "Keep this easy and save rhythm for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.18,
          structure: "3 x 12 min marathon rhythm with easy jog recovery",
          purpose: "Build confidence locking into controlled marathon effort.",
          executionTip: "This should feel patient, economical, and repeatable.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 720, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Add aerobic volume that supports marathon pace confidence.",
          executionTip: "Keep this comfortably controlled and below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Maintain relaxed mechanics without adding a second workout.",
          executionTip: "Keep the run very easy and the strides light.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.31,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Extend endurance while marathon-rhythm work stays controlled.",
          executionTip: "Let the duration be the stimulus; do not chase pace.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      loadMultiplier: 0.98,
      focus: "Absorb the opening aerobic block",
      coachNote: "Volume and intensity step down so the next block can progress without carrying fatigue.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while lowering training stress.",
          executionTip: "Err on the easy side and finish fresh.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.17,
          structure: "Controlled progression tempo",
          purpose: "Keep rhythm present without a heavy threshold load.",
          executionTip: "Progress gradually and finish feeling like you could do more.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 480, intensity: "TEMPO", intensityKey: "tempo" },
                  { sec: 300, intensity: "THRESHOLD", intensityKey: "threshold" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy medium-long run",
          purpose: "Preserve aerobic support without adding strain.",
          executionTip: "Keep this easier than your usual medium-long run.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run",
          purpose: "Keep frequency without adding load.",
          executionTip: "Short, soft, and easy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.29,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while recovery catches up.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      loadMultiplier: 1.1,
      focus: "Raise threshold support",
      coachNote: "Threshold volume expands while the medium-long run keeps aerobic durability high.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the larger threshold session.",
          executionTip: "Keep it smooth and avoid adding extra intensity.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.19,
          structure: "4 x 10 min threshold with easy jog recoveries",
          purpose: "Build threshold volume for sustained marathon strength.",
          executionTip: "Repeatable pressure only. No single rep should feel heroic.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 600, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Add aerobic durability that complements threshold work.",
          executionTip: "Keep this smooth and never harder than steady.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Maintain light leg speed without adding another workout.",
          executionTip: "Float the strides and recover fully between them.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Easy long run with fuelling practice",
          purpose: "Continue the long-run build while rehearsing race-day fuelling habits.",
          executionTip: "Keep this aerobic and practise fuelling before you feel depleted.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      loadMultiplier: 1.16,
      focus: "Build marathon-pace confidence",
      coachNote: "Marathon-rhythm blocks grow while the long run and medium-long run build durable volume.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support before the race-rhythm workout.",
          executionTip: "Stay relaxed and leave rhythm for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.19,
          structure: "4 x 12 min marathon rhythm with easy jog recoveries",
          purpose: "Build confidence holding goal rhythm in repeatable pieces.",
          executionTip: "Controlled from the first rep. Smooth matters more than fast.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 720, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Strengthen aerobic durability while staying below threshold.",
          executionTip: "Hold relaxed form and keep the effort sustainable.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run",
          purpose: "Keep frequency without stacking fatigue.",
          executionTip: "Easy enough that it helps the week, not adds to it.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build endurance and practise race-day fuelling habits.",
          executionTip: "Keep the run easy and practise regular fuel and fluid intake.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "BUILD",
      loadMultiplier: 1.24,
      focus: "Peak early threshold and long-run durability",
      coachNote: "This is a strong aerobic week anchored by sustained threshold work and a longer long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep easy volume present before the larger threshold session.",
          executionTip: "Stay relaxed and avoid adding pace.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.19,
          structure: "3 x 15 min threshold with easy jog recoveries",
          purpose: "Build sustained aerobic power for holding form deep into the marathon.",
          executionTip: "Keep the first rep controlled enough that the third is composed.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 900, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Add durable aerobic volume without turning the week into a second workout.",
          executionTip: "Stay smooth, patient, and below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep mechanics sharp while the workload rises.",
          executionTip: "Keep the run very easy and the strides relaxed.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_steady",
          targetShare: 0.33,
          longRunCapKm,
          structure: "Long run with steady finish and fuelling practice",
          purpose: "Extend endurance and practise controlled late-run rhythm.",
          executionTip: "Keep most of this easy; finish steady only if controlled and well fuelled.",
          workout: {
            kind: "LONG",
            variant: "STEADY_FINISH",
          },
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "DELOAD",
      loadMultiplier: 1.08,
      focus: "Consolidate before the marathon-specific block",
      coachNote: "A second deload keeps the 18-week build sustainable before the specific marathon work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Relaxed deload easy run",
          purpose: "Absorb the previous build while maintaining routine.",
          executionTip: "Keep it light and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.17,
          structure: "2 x 10 min steady with easy jog recovery",
          purpose: "Keep rhythm present without heavy fatigue.",
          executionTip: "Stay controlled and finish fresher than normal.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 600, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy medium-long run",
          purpose: "Preserve aerobic support while reducing strain.",
          executionTip: "Keep this easier than your usual medium-long run.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run",
          purpose: "Keep five-run rhythm without adding load.",
          executionTip: "Short and restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.29,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Protect recovery before the final race-specific build.",
          executionTip: "Finish fresher than usual.",
        },
      ],
    },
    {
      weekNumber: 9,
      phase: "SPECIFIC",
      loadMultiplier: 1.2,
      focus: "Build marathon-pace confidence",
      coachNote: "The main workout now targets marathon rhythm more directly while the long run reaches a stronger support distance.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the key marathon-rhythm session.",
          executionTip: "Keep this truly easy and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.19,
          structure: "4 x 15 min marathon rhythm with easy jog recovery",
          purpose: "Practise controlled race rhythm in repeatable blocks.",
          executionTip: "Hold back early. The final rep should still feel composed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 900, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability during the specific block.",
          executionTip: "Keep the rhythm smooth and avoid threshold effort.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep the legs responsive without adding fatigue.",
          executionTip: "Relaxed mechanics only; no sprinting.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build race confidence through a longer controlled aerobic effort.",
          executionTip: "Keep it aerobic from the start and practise fuel and fluid timing.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 10,
      phase: "SPECIFIC",
      loadMultiplier: 1.28,
      focus: "Build long-run quality",
      coachNote: "A steady threshold-support workout pairs with a long run that introduces marathon-rhythm blocks.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support present without adding fatigue.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "3 x 12 min threshold with easy jog recoveries",
          purpose: "Maintain threshold support while marathon-specific endurance grows.",
          executionTip: "Keep this controlled and slightly fresher than peak threshold weeks.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 720, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Keep aerobic durability high while staying controlled.",
          executionTip: "Smooth and controlled; avoid forcing pace.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run",
          purpose: "Absorb the specific block without adding strain.",
          executionTip: "Very relaxed and restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: marathonPace,
          targetShare: 0.34,
          longRunCapKm,
          structure: "Long run with 3 x 10 min marathon rhythm",
          purpose: "Build controlled race rhythm under long-run fatigue.",
          executionTip: "Keep most of this easy; make the marathon-rhythm blocks smooth and well fuelled.",
          workout: {
            kind: "LONG",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 300, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 11,
      phase: "SPECIFIC",
      loadMultiplier: 1.36,
      focus: "Peak marathon-pace volume",
      coachNote: "This is a key marathon-rhythm week supported by a steady medium-long run and a strong long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the key marathon-rhythm session.",
          executionTip: "Keep it smooth and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.20,
          structure: "3 x 20 min marathon rhythm with easy jog recovery",
          purpose: "Practise sustained marathon effort in controlled, repeatable blocks.",
          executionTip: "Hold back early. The final rep should still feel composed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 1200, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 240, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability in the peak block.",
          executionTip: "Keep this smooth and comfortably below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.11,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep mechanics sharp while fatigue is highest.",
          executionTip: "Run very easy and keep the strides relaxed.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build race confidence through a longer controlled aerobic effort.",
          executionTip: "Keep this aerobic from the start and execute your fuelling plan.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 12,
      phase: "DELOAD",
      loadMultiplier: 1.2,
      focus: "Recover after the first specific peak",
      coachNote: "This deload protects adaptation after the first larger marathon-specific block.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while fatigue drops.",
          executionTip: "Keep it easy and avoid making up distance.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.17,
          structure: "2 x 12 min steady with easy jog recovery",
          purpose: "Keep a little rhythm without heavy load.",
          executionTip: "Stay smooth and finish feeling fresh.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 720, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy medium-long run",
          purpose: "Keep aerobic support while lowering strain.",
          executionTip: "Relaxed and controlled is enough.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run",
          purpose: "Keep five-run rhythm while recovery catches up.",
          executionTip: "Short and relaxed.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.29,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while recovery catches up.",
          executionTip: "Finish fresher than usual.",
        },
      ],
    },
    {
      weekNumber: 13,
      phase: "SPECIFIC",
      loadMultiplier: 1.32,
      focus: "Final threshold support before peak long-run quality",
      coachNote: "Threshold support is maintained before the final heavy marathon-specific long-run block.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support before the threshold-support workout.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "2 x 20 min threshold with easy jog recovery",
          purpose: "Support marathon pace with strong but controlled aerobic pressure.",
          executionTip: "Keep this smooth and controlled; do not force threshold late.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 1200, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 240, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability as the final build approaches.",
          executionTip: "Keep this controlled and avoid threshold effort.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Maintain relaxed mechanics without adding strain.",
          executionTip: "Keep the strides light and controlled.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build durable endurance before the peak long-run quality week.",
          executionTip: "Keep this aerobic and practise fuelling from early in the run.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 14,
      phase: "SPECIFIC",
      loadMultiplier: 1.4,
      focus: "Peak long-run quality and fuelling rehearsal",
      coachNote: "This is the peak marathon-specific long run, with controlled marathon-rhythm blocks and full fuelling practice.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support while the long run becomes the key session.",
          executionTip: "Keep this genuinely easy and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.18,
          structure: "2 x 25 min marathon rhythm with easy jog recovery",
          purpose: "Rehearse sustained marathon rhythm without overloading the week.",
          executionTip: "This should feel economical and confidence-building, not hard.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 1500, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 240, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability without making the week too sharp.",
          executionTip: "Keep it smooth and controlled.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.11,
          structure: "Recovery run",
          purpose: "Absorb the final peak workload.",
          executionTip: "Very relaxed and restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: marathonPace,
          targetShare: 0.36,
          longRunCapKm,
          structure: "Peak long run with 4 x 15 min marathon rhythm",
          purpose: "Rehearse race rhythm under controlled long-run fatigue.",
          executionTip: "Keep most of this easy, execute fuelling, and make the marathon-rhythm blocks smooth.",
          workout: {
            kind: "LONG",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 900, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 300, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 15,
      phase: "SPECIFIC",
      loadMultiplier: 1.22,
      focus: "Consolidate race confidence before taper",
      coachNote: "The long run comes down slightly while controlled marathon rhythm reinforces confidence before taper.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support present without adding fatigue.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.18,
          structure: "3 x 12 min controlled marathon rhythm with easy jog recovery",
          purpose: "Keep marathon rhythm familiar while reducing total stress.",
          executionTip: "Smooth and controlled. This should feel fresher than the peak block.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 720, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability as taper approaches.",
          executionTip: "Keep this controlled and avoid forcing pace.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep mechanics relaxed before taper.",
          executionTip: "Keep the run easy and strides light.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.34,
          longRunCapKm,
          structure: "Reduced long run with fuelling practice",
          purpose: "Preserve endurance while allowing freshness to start building.",
          executionTip: "Keep this mostly easy and practise only the fuelling routine you trust.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 16,
      phase: "TAPER",
      loadMultiplier: 1,
      focus: "Begin taper while keeping rhythm",
      coachNote: "The workload comes down so freshness can build while one controlled session maintains confidence.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support without adding fatigue.",
          executionTip: "This should feel lighter than the previous build weeks.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.17,
          structure: "3 x 8 min controlled marathon rhythm with easy jog recovery",
          purpose: "Rehearse race rhythm in short controlled pieces.",
          executionTip: "Keep this smooth and confidence-building. Do not chase faster-than-goal effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 480, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Short steady medium run",
          purpose: "Keep rhythm alive while taper begins.",
          executionTip: "Controlled only; stay fresher than normal.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run with 4 relaxed strides",
          purpose: "Stay loose without adding fatigue.",
          executionTip: "Keep the strides relaxed and stop well short of sprinting.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while taper begins.",
          executionTip: "Shorter and easier is the correct execution.",
        },
      ],
    },
    {
      weekNumber: 17,
      phase: "TAPER",
      loadMultiplier: 0.74,
      focus: "Freshen up and protect confidence",
      coachNote: "Volume drops again while short rhythm work keeps marathon effort familiar.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.22,
          structure: "Easy aerobic run",
          purpose: "Maintain routine while building freshness.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.16,
          structure: "2 x 6 min controlled marathon rhythm with easy jog recovery",
          purpose: "Keep race rhythm present without adding fatigue.",
          executionTip: "Smooth and light. This is not a test.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 360, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Very easy support run",
          purpose: "Keep the legs moving while preserving freshness.",
          executionTip: "Relaxed only. No extra work.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Short recovery run",
          purpose: "Keep five-run rhythm without carrying fatigue.",
          executionTip: "Short, relaxed, and optional if rest would help more.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Short reduced long run",
          purpose: "Maintain confidence without carrying fatigue into race week.",
          executionTip: "Keep this easy and controlled from the first step.",
        },
      ],
    },
    {
      weekNumber: 18,
      phase: "TAPER",
      loadMultiplier: 0.55,
      focus: "Stay fresh and race the marathon",
      coachNote: "Race week keeps the legs moving early, adds a light marathon-rhythm tune-up, then protects freshness for race day.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.10,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.10,
          structure: "5 x 2 min relaxed marathon rhythm with easy jog recovery",
          purpose: "Prime race rhythm without creating workout-level fatigue.",
          executionTip: "Controlled and light. This is a confidence tune-up, not a test.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 5,
                work: { valueSec: 120, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.08,
          structure: "Very short easy shakeout",
          purpose: "Keep the legs responsive while staying fresh.",
          executionTip: "Keep this short and relaxed with no extra work.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.07,
          structure: "Optional recovery jog",
          purpose: "Stay loose only if it helps you feel fresher.",
          executionTip: "Skip this if freshness would be better served by rest.",
        },
        {
          role: "race",
          type: "RACE",
          target: marathonPace,
          targetShare: 0.65,
          fixedDistanceKm: 42.2,
          structure: "Marathon race or timed 42.2K effort",
          purpose: "Execute the target marathon effort with controlled pacing and practised fuelling.",
          executionTip: "Start patient, fuel early, settle into rhythm, and aim to finish composed.",
          workout: {
            kind: "RACE",
            fixedDistanceKm: 42.2,
            label: "Marathon race",
          },
        },
      ],
    },
  ],
};

export default template;
