const easy = "easy";
const steady = "steady";
const marathonPace = "race_pace";

const longRunCapKm = 32;

const template = {
  id: "marathon_beginner_16w_4run",
  metadata: {
    distance: "MARATHON",
    level: "beginner",
    weeks: 16,
    runsPerWeek: 4,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      loadMultiplier: 1,
      focus: "Build a repeatable four-run marathon rhythm",
      coachNote: "Start with easy running, one steady support run, and a controlled long run so the routine feels sustainable.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.23,
          structure: "Easy aerobic run",
          purpose: "Build consistency without adding fatigue.",
          executionTip: "Keep this relaxed enough that you could hold a full conversation.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.23,
          structure: "2 x 8 min steady with easy jog recovery",
          purpose: "Introduce controlled aerobic rhythm without aggressive intensity.",
          executionTip: "Stay smooth and patient. The reps should feel comfortably repeatable.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 480, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy support run",
          purpose: "Add low-stress frequency and make four runs per week feel normal.",
          executionTip: "Short and easy is the goal. Finish feeling better than when you started.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.34,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Begin building the endurance needed for marathon training.",
          executionTip: "Run by effort and keep the final third controlled.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      loadMultiplier: 1.05,
      focus: "Extend easy durability",
      coachNote: "The week stays mostly easy while the long run edges forward conservatively.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.23,
          structure: "Easy aerobic run",
          purpose: "Continue building aerobic consistency.",
          executionTip: "Stay conversational and avoid drifting into steady effort.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.23,
          structure: "20 min continuous steady run",
          purpose: "Build confidence holding a smooth aerobic rhythm.",
          executionTip: "Start slightly easier than you think and settle into steady effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy support run with 4 relaxed strides",
          purpose: "Keep frequency steady and maintain relaxed mechanics.",
          executionTip: "Strides are quick and relaxed, not sprints.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.34,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Gradually extend endurance while keeping the load manageable.",
          executionTip: "Keep the pace easy enough that you could add a few minutes if needed.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      loadMultiplier: 1.1,
      focus: "Build aerobic durability",
      coachNote: "The long run grows while steady running remains controlled and aerobic.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.22,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume steady before the steady session.",
          executionTip: "Stay relaxed and leave the controlled rhythm for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.24,
          structure: "2 x 10 min steady with easy jog recovery",
          purpose: "Build durable aerobic rhythm without interval stress.",
          executionTip: "Controlled only. You should finish each rep feeling like you could do one more.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 600, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run",
          purpose: "Keep frequency steady without increasing intensity.",
          executionTip: "Stay relaxed and controlled from start to finish.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Build confidence over a longer relaxed effort.",
          executionTip: "Keep it smooth and avoid pushing just because the distance is growing.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      loadMultiplier: 0.9,
      focus: "Absorb the first endurance block",
      coachNote: "This deload lowers strain while preserving the four-run routine.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.26,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while lowering training stress.",
          executionTip: "Err on the easy side and keep cadence relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.21,
          structure: "Light easy-to-steady progression",
          purpose: "Keep rhythm without making the deload hard.",
          executionTip: "Only progress to steady if the run feels comfortable.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 720, intensity: "EASY", intensityKey: "easy" },
                  { sec: 480, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Short easy support run",
          purpose: "Keep four-run frequency while protecting the deload.",
          executionTip: "Do not make up volume. Keep this relaxed.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while recovery catches up.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      loadMultiplier: 1.14,
      focus: "Resume long-run progression",
      coachNote: "The long run builds again, while weekday running stays controlled and aerobic.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.22,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the longer steady session.",
          executionTip: "Keep it smooth and avoid adding extra pace.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.24,
          structure: "2 x 12 min steady with easy jog recovery",
          purpose: "Build durable aerobic rhythm without aggressive intervals.",
          executionTip: "Stay patient. The goal is even rhythm, not speed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 720, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run with 4 relaxed strides",
          purpose: "Maintain relaxed mechanics while the long run grows.",
          executionTip: "Keep the strides light and controlled.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Continue the long-run build while weekday quality remains controlled.",
          executionTip: "Keep this aerobic; the steady session is the controlled work for the week.",
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      loadMultiplier: 1.2,
      focus: "Introduce marathon fuelling practice",
      coachNote: "The long run continues to build and now includes simple fuelling practice.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Easy aerobic run",
          purpose: "Maintain aerobic support before the steady session.",
          executionTip: "Keep the run relaxed and controlled.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.24,
          structure: "30 min continuous steady run",
          purpose: "Build confidence holding a smooth aerobic rhythm.",
          executionTip: "Start slightly easier than steady and settle into a patient rhythm.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 900, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 900, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run",
          purpose: "Add low-stress volume around the longer steady work.",
          executionTip: "Stay conversational throughout.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.36,
          longRunCapKm,
          structure: "Easy long run with fuelling practice",
          purpose: "Build endurance and start practising race-day fuelling habits.",
          executionTip: "Keep the run easy and practise small, regular fuel and fluid intake.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "BUILD",
      loadMultiplier: 1.26,
      focus: "Extend endurance and steady confidence",
      coachNote: "This is a stronger aerobic week, still without aggressive speed work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic volume consistent before the steady support work.",
          executionTip: "Stay conversational and leave extra effort out of this run.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.24,
          structure: "3 x 10 min steady with easy jog recoveries",
          purpose: "Build aerobic durability in controlled pieces.",
          executionTip: "Keep every rep smooth and finish with more in reserve.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Easy run with steady finish",
          purpose: "Build aerobic durability without turning the week into hard training.",
          executionTip: "Only finish steady if the early miles feel relaxed.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 900, intensity: "EASY", intensityKey: "easy" },
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.37,
          longRunCapKm,
          structure: "Easy long run with fuelling practice",
          purpose: "Extend endurance while rehearsing simple fuelling.",
          executionTip: "Keep effort easy and practise the fuel timing you may use on race day.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "DELOAD",
      loadMultiplier: 1,
      focus: "Consolidate before the marathon-specific block",
      coachNote: "A second deload keeps the 16-week build sustainable and lowers injury risk.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.26,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while absorbing the previous build.",
          executionTip: "Keep it light and avoid making up distance.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.21,
          structure: "2 x 8 min steady with easy jog recovery",
          purpose: "Keep controlled rhythm present without adding heavy load.",
          executionTip: "Stay controlled and finish fresher than normal.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 480, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Short easy support run",
          purpose: "Keep frequency while recovery catches up.",
          executionTip: "Short and easy is enough.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while preparing for the specific block.",
          executionTip: "Finish fresh and controlled.",
        },
      ],
    },
    {
      weekNumber: 9,
      phase: "SPECIFIC",
      loadMultiplier: 1.34,
      focus: "Introduce marathon-rhythm confidence",
      coachNote: "Marathon rhythm appears in controlled pieces while the long run continues its conservative build.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the marathon-rhythm workout.",
          executionTip: "Keep this truly easy and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.23,
          structure: "3 x 12 min marathon rhythm with easy jog recovery",
          purpose: "Practise controlled marathon effort without a heavy workout load.",
          executionTip: "This should feel patient, economical, and repeatable.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 720, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run with 4 relaxed strides",
          purpose: "Maintain relaxed mechanics during the specific block.",
          executionTip: "Keep the strides relaxed and controlled.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.38,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build race confidence through a longer controlled aerobic effort.",
          executionTip: "Keep it aerobic and practise fuel and fluid timing from early in the run.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 10,
      phase: "SPECIFIC",
      loadMultiplier: 1.42,
      focus: "Build long-run durability",
      coachNote: "This week is about durable endurance, not speed.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support present without adding fatigue.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.23,
          structure: "35 min continuous steady run",
          purpose: "Improve aerobic durability for the middle miles of the marathon.",
          executionTip: "Keep this controlled. It should never feel like a race effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 1050, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 1050, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Easy run with steady finish",
          purpose: "Add controlled aerobic strength while staying beginner-safe.",
          executionTip: "Keep most of this easy; only finish steady if it feels comfortable.",
          workout: {
            kind: "EASY",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 900, intensity: "EASY", intensityKey: "easy" },
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                ],
              },
            ],
          },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.39,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build durable endurance and rehearse race-day fuelling habits.",
          executionTip: "Keep effort easy and practise fuelling before you feel depleted.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 11,
      phase: "SPECIFIC",
      loadMultiplier: 1.5,
      focus: "Peak marathon-specific confidence",
      coachNote: "This is the biggest endurance-support week, with marathon rhythm and a confident long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the key marathon-rhythm session.",
          executionTip: "Keep it smooth and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.23,
          structure: "3 x 15 min marathon rhythm with easy jog recovery",
          purpose: "Practise marathon effort in controlled, repeatable blocks.",
          executionTip: "Hold back early. The final rep should still feel composed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 900, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy support run",
          purpose: "Keep frequency high while the marathon-specific work absorbs.",
          executionTip: "Keep this relaxed enough to recover well.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.40,
          longRunCapKm,
          structure: "Peak long run with fuelling practice",
          purpose: "Build race confidence through the longest controlled aerobic effort.",
          executionTip: "Keep this aerobic from the start and execute your fuelling plan.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 12,
      phase: "DELOAD",
      loadMultiplier: 1.12,
      focus: "Recover after the peak endurance week",
      coachNote: "This deload protects adaptation after the largest long-run block.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.25,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while fatigue drops.",
          executionTip: "Keep it easy and avoid making up distance.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.21,
          structure: "2 x 10 min steady with easy jog recovery",
          purpose: "Keep a little rhythm without heavy load.",
          executionTip: "Stay smooth and finish feeling fresh.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 600, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Short easy support run",
          purpose: "Keep four-run rhythm while lowering strain.",
          executionTip: "Short and relaxed is the goal.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while recovery catches up.",
          executionTip: "Finish fresher than usual.",
        },
      ],
    },
    {
      weekNumber: 13,
      phase: "SPECIFIC",
      loadMultiplier: 1.44,
      focus: "Final marathon confidence block",
      coachNote: "This is the final specific build before taper, with controlled marathon rhythm and a reduced-but-meaningful long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support before the final race-rhythm workout.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.23,
          structure: "2 x 20 min marathon rhythm with easy jog recovery",
          purpose: "Rehearse marathon effort without extending the workout too far.",
          executionTip: "This should feel economical and confidence-building, not hard.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 1200, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 240, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy support run with 4 relaxed strides",
          purpose: "Maintain relaxed mechanics as taper approaches.",
          executionTip: "Keep the strides light and controlled.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_marathon_rhythm",
          targetShare: 0.38,
          longRunCapKm,
          structure: "Long run with short marathon-rhythm finish",
          purpose: "Build final race confidence while keeping most of the run easy.",
          executionTip: "Keep most of this easy; finish at marathon rhythm only if controlled and well fuelled.",
          workout: {
            kind: "LONG",
            variant: "MARATHON_FINISH",
          },
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 14,
      phase: "TAPER",
      loadMultiplier: 1.05,
      focus: "Begin taper while keeping rhythm",
      coachNote: "The workload comes down so freshness can build while one controlled session maintains confidence.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.24,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support without adding fatigue.",
          executionTip: "This should feel lighter than the previous build weeks.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.22,
          structure: "3 x 8 min controlled marathon rhythm with easy jog recovery",
          purpose: "Rehearse race rhythm in short controlled pieces.",
          executionTip: "Keep this smooth and confidence-building. Do not chase faster-than-goal effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 480, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Short easy support run",
          purpose: "Keep four-run frequency while fatigue falls.",
          executionTip: "Keep this relaxed and short.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while taper begins.",
          executionTip: "Shorter and easier is the correct execution.",
        },
      ],
    },
    {
      weekNumber: 15,
      phase: "TAPER",
      loadMultiplier: 0.78,
      focus: "Freshen up and protect confidence",
      coachNote: "Volume drops again while a short rhythm session keeps the legs familiar with marathon effort.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.27,
          structure: "Easy aerobic run",
          purpose: "Maintain routine while building freshness.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.20,
          structure: "2 x 6 min controlled marathon rhythm with easy jog recovery",
          purpose: "Keep race rhythm present without adding fatigue.",
          executionTip: "Smooth and light. This is not a test.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 360, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Very easy support run",
          purpose: "Keep the legs moving while preserving freshness.",
          executionTip: "Relaxed only. No extra work.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.34,
          longRunCapKm,
          structure: "Short reduced long run",
          purpose: "Maintain confidence without carrying fatigue into race week.",
          executionTip: "Keep this easy and controlled from the first step.",
        },
      ],
    },
    {
      weekNumber: 16,
      phase: "TAPER",
      loadMultiplier: 0.52,
      focus: "Stay fresh and complete the marathon",
      coachNote: "Race week keeps the legs moving early, then protects freshness for the marathon effort.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.10,
          structure: "4 x 2 min relaxed marathon rhythm with easy jog recovery",
          purpose: "Prime race rhythm without creating workout-level fatigue.",
          executionTip: "Controlled and light. This is a confidence tune-up, not a test.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 120, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.08,
          structure: "Very short easy shakeout",
          purpose: "Keep the legs responsive while staying fresh.",
          executionTip: "Keep this short and relaxed with no extra work.",
        },
        {
          role: "race",
          type: "RACE",
          target: marathonPace,
          targetShare: 0.70,
          fixedDistanceKm: 42.2,
          structure: "Marathon race or timed 42.2K effort",
          purpose: "Complete the target marathon effort with controlled pacing and practised fuelling.",
          executionTip: "Start patient, fuel early, settle into rhythm, and aim to finish composed.",
          workout: {
            kind: "RACE",
            fixedDistanceKm: 42.2,
            label: "Marathon race",
          },
        },
      ],
    },
  ],
};

export default template;
