const easy = "easy";
const steady = "steady";
const threshold = "threshold";
const marathonPace = "race_pace";

const longRunCapKm = 34;

const template = {
  id: "marathon_intermediate_16w_5run",
  metadata: {
    distance: "MARATHON",
    level: "intermediate",
    weeks: 16,
    runsPerWeek: 5,
  },
  weeks: [
    {
      weekNumber: 1,
      phase: "BASE",
      loadMultiplier: 1,
      focus: "Establish five-run marathon rhythm",
      coachNote: "Start with easy volume, controlled threshold support, a steady medium-long run, and an easy long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy aerobic run",
          purpose: "Build aerobic volume without adding fatigue.",
          executionTip: "Keep this genuinely easy so the threshold session stays controlled.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "3 x 8 min threshold with easy jog recoveries",
          purpose: "Build sustainable aerobic strength that supports marathon pace.",
          executionTip: "Stay smooth and repeatable. Do not turn this into a race effort.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 480, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Build aerobic durability without making a second hard workout.",
          executionTip: "Keep this below threshold; smooth and sustainable is the aim.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Add frequency and relaxed mechanics while absorbing the main session.",
          executionTip: "Run very easy, then keep the strides loose and controlled.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Start the marathon long-run build from a controlled aerobic base.",
          executionTip: "Run by effort and keep the final third comfortable.",
        },
      ],
    },
    {
      weekNumber: 2,
      phase: "BASE",
      loadMultiplier: 1.05,
      focus: "Extend aerobic durability",
      coachNote: "The week keeps a steady medium-long run and lengthens the controlled threshold support.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Easy aerobic run",
          purpose: "Maintain easy aerobic volume before the longer controlled work.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "2 x 12 min threshold with easy jog recovery",
          purpose: "Build longer sustainable efforts that support marathon economy.",
          executionTip: "Hold the same effort through both reps; avoid forcing the second one.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 720, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Build aerobic durability while staying below threshold.",
          executionTip: "Smooth and patient. This should never feel like a workout.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run",
          purpose: "Keep frequency high while letting the quality work absorb.",
          executionTip: "Run softer than normal if your legs feel heavy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Gradually extend time on feet with controlled effort.",
          executionTip: "Keep the effort even and avoid pushing the finish.",
        },
      ],
    },
    {
      weekNumber: 3,
      phase: "BUILD",
      loadMultiplier: 1.1,
      focus: "Introduce marathon-rhythm confidence",
      coachNote: "Marathon rhythm appears in repeatable blocks while the long run continues to build.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the first marathon-rhythm workout.",
          executionTip: "Keep this easy and save rhythm for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.18,
          structure: "3 x 10 min marathon rhythm with easy jog recovery",
          purpose: "Build confidence locking into controlled marathon effort.",
          executionTip: "This should feel patient, economical, and repeatable.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Add aerobic volume that supports marathon pace confidence.",
          executionTip: "Keep this comfortably controlled and below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Maintain relaxed mechanics without adding a second workout.",
          executionTip: "Keep the run very easy and the strides light.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Easy long run",
          purpose: "Extend endurance while the marathon-rhythm work stays controlled.",
          executionTip: "Let the duration be the stimulus; do not chase pace.",
        },
      ],
    },
    {
      weekNumber: 4,
      phase: "DELOAD",
      loadMultiplier: 0.9,
      focus: "Absorb the first aerobic block",
      coachNote: "Volume and intensity step down so the next block can build from a fresher base.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while lowering training stress.",
          executionTip: "Err on the easy side and finish fresh.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.17,
          structure: "Light progression tempo",
          purpose: "Keep rhythm present without a heavy threshold load.",
          executionTip: "Progress gradually and finish feeling like you could do more.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "PROGRESSIVE",
                segments: [
                  { sec: 600, intensity: "STEADY", intensityKey: "steady" },
                  { sec: 480, intensity: "TEMPO", intensityKey: "tempo" },
                  { sec: 300, intensity: "THRESHOLD", intensityKey: "threshold" },
                ],
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy medium-long run",
          purpose: "Preserve aerobic support without adding strain.",
          executionTip: "Keep this easier than your usual medium-long run.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run",
          purpose: "Keep frequency without adding load.",
          executionTip: "Short, soft, and easy.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.29,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Keep endurance ticking while recovery catches up.",
          executionTip: "Finish fresher than usual; this is a consolidation run.",
        },
      ],
    },
    {
      weekNumber: 5,
      phase: "BUILD",
      loadMultiplier: 1.14,
      focus: "Raise threshold support and long-run durability",
      coachNote: "Threshold support lengthens while the medium-long run keeps aerobic volume strong.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.17,
          structure: "Easy aerobic run",
          purpose: "Support recovery before longer threshold work.",
          executionTip: "Keep it smooth and avoid adding extra intensity.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "3 x 10 min threshold with easy jog recoveries",
          purpose: "Build threshold volume for sustained marathon strength.",
          executionTip: "Repeatable pressure only. No single rep should feel heroic.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Add aerobic durability that complements threshold work.",
          executionTip: "Keep this smooth and never harder than steady.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Maintain light leg speed without adding another workout.",
          executionTip: "Float the strides and recover fully between them.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Easy long run with fuelling practice",
          purpose: "Continue the long-run build while rehearsing race-day fuelling habits.",
          executionTip: "Keep this aerobic and practise fuelling before you feel depleted.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 6,
      phase: "BUILD",
      loadMultiplier: 1.2,
      focus: "Build marathon-pace confidence",
      coachNote: "Marathon-rhythm blocks grow while the long run and medium-long run build durable volume.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support before the race-rhythm workout.",
          executionTip: "Stay relaxed and leave rhythm for the quality day.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.19,
          structure: "4 x 10 min marathon rhythm with easy jog recoveries",
          purpose: "Build confidence holding goal rhythm in repeatable pieces.",
          executionTip: "Controlled from the first rep. Smooth matters more than fast.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 4,
                work: { valueSec: 600, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Strengthen aerobic durability while staying below threshold.",
          executionTip: "Hold relaxed form and keep the effort sustainable.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run",
          purpose: "Keep frequency without stacking fatigue.",
          executionTip: "Easy enough that it helps the week, not adds to it.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build endurance and practise race-day fuelling habits.",
          executionTip: "Keep the run easy and practise regular fuel and fluid intake.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 7,
      phase: "BUILD",
      loadMultiplier: 1.26,
      focus: "Peak early threshold support",
      coachNote: "This is a strong aerobic week anchored by sustained threshold work and a longer long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep easy volume present before the larger threshold session.",
          executionTip: "Stay relaxed and avoid adding pace.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.19,
          structure: "2 x 18 min threshold with easy jog recovery",
          purpose: "Build sustained aerobic power for holding form deep into the marathon.",
          executionTip: "Keep the first rep controlled enough that the second is composed.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 1080, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Add durable aerobic volume without turning the week into a second workout.",
          executionTip: "Stay smooth, patient, and below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep mechanics sharp while the workload rises.",
          executionTip: "Keep the run very easy and the strides relaxed.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Extend endurance while rehearsing fuel timing.",
          executionTip: "Keep this aerobic and execute your fuelling plan early.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 8,
      phase: "DELOAD",
      loadMultiplier: 1,
      focus: "Consolidate before the marathon-specific block",
      coachNote: "A second deload keeps the 16-week build sustainable before the specific marathon work.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Relaxed deload easy run",
          purpose: "Absorb the previous build while maintaining routine.",
          executionTip: "Keep it light and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.17,
          structure: "2 x 10 min steady with easy jog recovery",
          purpose: "Keep rhythm present without heavy fatigue.",
          executionTip: "Stay controlled and finish fresher than normal.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 600, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy medium-long run",
          purpose: "Preserve aerobic support while reducing strain.",
          executionTip: "Keep this easier than your usual medium-long run.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run",
          purpose: "Keep five-run rhythm without adding load.",
          executionTip: "Short and restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.29,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Protect recovery before the final race-specific build.",
          executionTip: "Finish fresher than usual.",
        },
      ],
    },
    {
      weekNumber: 9,
      phase: "SPECIFIC",
      loadMultiplier: 1.32,
      focus: "Build marathon-pace confidence",
      coachNote: "The main workout now targets marathon rhythm more directly while the long run reaches a stronger support distance.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the key marathon-rhythm session.",
          executionTip: "Keep this truly easy and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.19,
          structure: "3 x 15 min marathon rhythm with easy jog recovery",
          purpose: "Practise controlled race rhythm in repeatable blocks.",
          executionTip: "Hold back early. The final rep should still feel composed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 900, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability during the specific block.",
          executionTip: "Keep the rhythm smooth and avoid threshold effort.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep the legs responsive without adding fatigue.",
          executionTip: "Relaxed mechanics only; no sprinting.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build race confidence through a longer controlled aerobic effort.",
          executionTip: "Keep it aerobic from the start and practise fuel and fluid timing.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 10,
      phase: "SPECIFIC",
      loadMultiplier: 1.4,
      focus: "Build long-run progression",
      coachNote: "This week emphasizes durable aerobic volume and a longer long run with fuelling practice.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support present without adding fatigue.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "THRESHOLD",
          target: threshold,
          targetShare: 0.18,
          structure: "3 x 12 min threshold with easy jog recoveries",
          purpose: "Maintain threshold support while marathon-specific endurance grows.",
          executionTip: "Keep this controlled and slightly fresher than peak threshold weeks.",
          workout: {
            kind: "THRESHOLD",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 720, intensity: "THRESHOLD", intensityKey: "threshold" },
                recover: { valueSec: 150, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.20,
          structure: "Steady medium-long run",
          purpose: "Keep aerobic durability high while staying controlled.",
          executionTip: "Smooth and controlled; avoid forcing pace.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run",
          purpose: "Absorb the specific block without adding strain.",
          executionTip: "Very relaxed and restorative.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.34,
          longRunCapKm,
          structure: "Long run with fuelling practice",
          purpose: "Build durable endurance and rehearse race-day fuelling habits.",
          executionTip: "Keep effort easy and practise fuelling before you feel depleted.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 11,
      phase: "SPECIFIC",
      loadMultiplier: 1.48,
      focus: "Peak marathon-specific confidence",
      coachNote: "This is the largest endurance-support week, with marathon rhythm and a confident long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.15,
          structure: "Easy aerobic run",
          purpose: "Support recovery before the key marathon-rhythm session.",
          executionTip: "Keep it smooth and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.20,
          structure: "3 x 20 min marathon rhythm with easy jog recovery",
          purpose: "Practise sustained marathon effort in controlled, repeatable blocks.",
          executionTip: "Hold back early. The final rep should still feel composed.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 1200, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 240, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability in the peak block.",
          executionTip: "Keep this smooth and comfortably below threshold.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.11,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Keep mechanics sharp while fatigue is highest.",
          executionTip: "Run very easy and keep the strides relaxed.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.35,
          longRunCapKm,
          structure: "Peak long run with fuelling practice",
          purpose: "Build race confidence through the longest controlled aerobic effort.",
          executionTip: "Keep this aerobic from the start and execute your fuelling plan.",
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 12,
      phase: "DELOAD",
      loadMultiplier: 1.12,
      focus: "Recover after the peak endurance week",
      coachNote: "This deload protects adaptation after the largest long-run block.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.21,
          structure: "Relaxed deload easy run",
          purpose: "Maintain routine while fatigue drops.",
          executionTip: "Keep it easy and avoid making up distance.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: steady,
          targetShare: 0.17,
          structure: "2 x 12 min steady with easy jog recovery",
          purpose: "Keep a little rhythm without heavy load.",
          executionTip: "Stay smooth and finish feeling fresh.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 720, intensity: "STEADY", intensityKey: "steady" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.20,
          structure: "Easy medium-long run",
          purpose: "Keep aerobic support while lowering strain.",
          executionTip: "Relaxed and controlled is enough.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run",
          purpose: "Keep five-run rhythm while recovery catches up.",
          executionTip: "Short and relaxed.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.29,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while recovery catches up.",
          executionTip: "Finish fresher than usual.",
        },
      ],
    },
    {
      weekNumber: 13,
      phase: "SPECIFIC",
      loadMultiplier: 1.42,
      focus: "Final marathon-specific build",
      coachNote: "This is the last meaningful build before taper, pairing marathon rhythm with a reduced-but-important long run.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.16,
          structure: "Easy aerobic run",
          purpose: "Keep aerobic support before the final race-rhythm workout.",
          executionTip: "Stay conversational and relaxed.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.19,
          structure: "2 x 25 min marathon rhythm with easy jog recovery",
          purpose: "Rehearse marathon effort without extending the workout too far.",
          executionTip: "This should feel economical and confidence-building, not hard.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 1500, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 240, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.19,
          structure: "Steady medium-long run",
          purpose: "Maintain aerobic durability as taper approaches.",
          executionTip: "Keep this controlled and avoid threshold effort.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Recovery run with 6 relaxed strides",
          purpose: "Maintain relaxed mechanics without adding strain.",
          executionTip: "Keep the strides light and controlled.",
          meta: { includeStrides: true, strides: 6 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: "easy_to_marathon_rhythm",
          targetShare: 0.34,
          longRunCapKm,
          structure: "Long run with 3 x 10 min marathon rhythm",
          purpose: "Build final race confidence while keeping most of the run easy.",
          executionTip: "Keep most of this easy; make the marathon-rhythm blocks smooth and well fuelled.",
          workout: {
            kind: "LONG",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 600, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 300, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
          meta: { fuellingPractice: true },
        },
      ],
    },
    {
      weekNumber: 14,
      phase: "TAPER",
      loadMultiplier: 1.05,
      focus: "Begin taper while keeping rhythm",
      coachNote: "The workload comes down so freshness can build while one controlled session maintains confidence.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.19,
          structure: "Easy aerobic run",
          purpose: "Keep routine and aerobic support without adding fatigue.",
          executionTip: "This should feel lighter than the previous build weeks.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.17,
          structure: "3 x 8 min controlled marathon rhythm with easy jog recovery",
          purpose: "Rehearse race rhythm in short controlled pieces.",
          executionTip: "Keep this smooth and confidence-building. Do not chase faster-than-goal effort.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 3,
                work: { valueSec: 480, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: steady,
          targetShare: 0.18,
          structure: "Short steady medium run",
          purpose: "Keep rhythm alive while taper begins.",
          executionTip: "Controlled only; stay fresher than normal.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.13,
          structure: "Short recovery run with 4 relaxed strides",
          purpose: "Stay loose without adding fatigue.",
          executionTip: "Keep the strides relaxed and stop well short of sprinting.",
          meta: { includeStrides: true, strides: 4 },
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.33,
          longRunCapKm,
          structure: "Reduced easy long run",
          purpose: "Preserve endurance while taper begins.",
          executionTip: "Shorter and easier is the correct execution.",
        },
      ],
    },
    {
      weekNumber: 15,
      phase: "TAPER",
      loadMultiplier: 0.78,
      focus: "Freshen up and protect confidence",
      coachNote: "Volume drops again while short rhythm work keeps marathon effort familiar.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.22,
          structure: "Easy aerobic run",
          purpose: "Maintain routine while building freshness.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.16,
          structure: "2 x 6 min controlled marathon rhythm with easy jog recovery",
          purpose: "Keep race rhythm present without adding fatigue.",
          executionTip: "Smooth and light. This is not a test.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 2,
                work: { valueSec: 360, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 180, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.18,
          structure: "Very easy support run",
          purpose: "Keep the legs moving while preserving freshness.",
          executionTip: "Relaxed only. No extra work.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.12,
          structure: "Short recovery run",
          purpose: "Keep five-run rhythm without carrying fatigue.",
          executionTip: "Short, relaxed, and optional if rest would help more.",
        },
        {
          role: "long_run",
          type: "LONG",
          target: easy,
          targetShare: 0.32,
          longRunCapKm,
          structure: "Short reduced long run",
          purpose: "Maintain confidence without carrying fatigue into race week.",
          executionTip: "Keep this easy and controlled from the first step.",
        },
      ],
    },
    {
      weekNumber: 16,
      phase: "TAPER",
      loadMultiplier: 0.55,
      focus: "Stay fresh and race the marathon",
      coachNote: "Race week keeps the legs moving early, adds a light marathon-rhythm tune-up, then protects freshness for race day.",
      sessions: [
        {
          role: "easy",
          type: "EASY",
          target: easy,
          targetShare: 0.10,
          structure: "Short easy run",
          purpose: "Stay loose without creating fatigue.",
          executionTip: "Keep it relaxed and finish wanting more.",
        },
        {
          role: "quality",
          type: "TEMPO",
          target: marathonPace,
          targetShare: 0.10,
          structure: "5 x 2 min relaxed marathon rhythm with easy jog recovery",
          purpose: "Prime race rhythm without creating workout-level fatigue.",
          executionTip: "Controlled and light. This is a confidence tune-up, not a test.",
          workout: {
            kind: "TEMPO",
            blocks: [
              {
                type: "REPEAT",
                repeatCount: 5,
                work: { valueSec: 120, intensity: "RACEPACE", intensityKey: "racepace" },
                recover: { valueSec: 120, intensity: "EASY", intensityKey: "easy" },
              },
            ],
          },
        },
        {
          role: "support",
          type: "EASY",
          target: easy,
          targetShare: 0.08,
          structure: "Very short easy shakeout",
          purpose: "Keep the legs responsive while staying fresh.",
          executionTip: "Keep this short and relaxed with no extra work.",
        },
        {
          role: "recovery",
          type: "EASY",
          target: easy,
          targetShare: 0.07,
          structure: "Optional recovery jog",
          purpose: "Stay loose only if it helps you feel fresher.",
          executionTip: "Skip this if freshness would be better served by rest.",
        },
        {
          role: "race",
          type: "RACE",
          target: marathonPace,
          targetShare: 0.65,
          fixedDistanceKm: 42.2,
          structure: "Marathon race or timed 42.2K effort",
          purpose: "Execute the target marathon effort with controlled pacing and practised fuelling.",
          executionTip: "Start patient, fuel early, settle into rhythm, and aim to finish composed.",
          workout: {
            kind: "RACE",
            fixedDistanceKm: 42.2,
            label: "Marathon race",
          },
        },
      ],
    },
  ],
};

export default template;
